import type { ExecutionDefinition } from '../types'
import { EXECUTION_LIBRARY_VERSION } from '../synthesis/semanticVersion'

const CURRENT_FORMALIZATION_SOURCE =
  'Current Elemental Work-Domain Taxonomy · product formalization'

const TRADITIONAL_SOURCE_URLS = [
  'https://ctext.org/huangdi-neijing/xuan-ming-wu-qi',
  'https://ctext.org/huangdi-neijing/ling-lan-mi-dian-lun/zh',
] as const

export const ELEMENTAL_EXECUTION_LIBRARY: readonly ExecutionDefinition[] = Object.freeze([
  {
    id: 'wood-direction-development',
    category: 'wood',
    elementCharacter: '木',
    elementPinyin: 'Mù',
    title: 'Direction & Development',
    spirit: {
      character: '魂',
      pinyin: 'Hún',
      classicalGloss: 'Ethereal soul',
      zangCorrespondence: 'liver',
    },
    description:
      'Strategic and generative work that establishes direction and opens a line of development.',
    taskDomains: [
      'Strategy and roadmapping',
      'Concept and creative development',
      'Exploratory research and opportunity discovery',
      'Prototyping and initiative formation',
      'Product, project, and capability development',
    ],
    relationAffinities: ['follow', 'transform', 'counterbalance'],
    directionAffinities: ['forward', 'circulating'],
    intentionAffinities: [
      'sui-responsive-following',
      'rou-yielding-softness',
      'tong-unobstructed-passage',
      'zhen-stable-constancy',
      'xing-timely-execution',
    ],
    strategicVectorAffinities: ['advance', 'adapt', 'clarify', 'nourish'],
    somaticVectorAffinities: ['maintain-rhythm', 'allow-space', 'restore-circulation'],
    macroAffinities: ['entering'],
    scope: 'ordinary-work-domain',
    formalization: 'current',
    sourceLabel: CURRENT_FORMALIZATION_SOURCE,
    sourceUrls: TRADITIONAL_SOURCE_URLS,
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'fire-communication-leadership',
    category: 'fire',
    elementCharacter: '火',
    elementPinyin: 'Huǒ',
    title: 'Communication & Leadership',
    spirit: {
      character: '神',
      pinyin: 'Shén',
      classicalGloss: 'Spirit',
      zangCorrespondence: 'heart',
    },
    description:
      'Relational and expressive work that makes decisions legible and aligns people in real time.',
    taskDomains: [
      'Writing, speaking, and presentations',
      'Meetings, facilitation, and collaboration',
      'Leadership and team alignment',
      'Teaching, mentoring, and knowledge transfer',
      'Stakeholder, client, and community engagement',
    ],
    relationAffinities: ['follow', 'counterbalance', 'complete'],
    directionAffinities: ['forward', 'circulating', 'releasing'],
    intentionAffinities: [
      'sui-responsive-following',
      'tong-unobstructed-passage',
      'ming-clear-discernment',
      'he-harmonizing-balance',
      'xing-timely-execution',
    ],
    strategicVectorAffinities: ['advance', 'clarify', 'adapt', 'complete'],
    somaticVectorAffinities: ['allow-space', 'maintain-rhythm', 'restore-circulation'],
    macroAffinities: ['entering'],
    scope: 'ordinary-work-domain',
    formalization: 'current',
    sourceLabel: CURRENT_FORMALIZATION_SOURCE,
    sourceUrls: TRADITIONAL_SOURCE_URLS,
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'earth-operations-stewardship',
    category: 'earth',
    elementCharacter: '土',
    elementPinyin: 'Tǔ',
    title: 'Operations & Stewardship',
    spirit: {
      character: '意',
      pinyin: 'Yì',
      classicalGloss: 'Intent',
      zangCorrespondence: 'spleen',
    },
    description:
      'Administrative and operational work that keeps accounts, schedules, records, resources, and recurring systems coherent.',
    taskDomains: [
      'Administration and scheduling',
      'Routine bookkeeping, invoicing, and expense reconciliation',
      'Documentation, recordkeeping, and data hygiene',
      'Operations, logistics, and procurement',
      'Workflow, inventory, and service maintenance',
    ],
    relationAffinities: ['contain', 'counterbalance', 'transform', 'wait'],
    directionAffinities: ['stabilizing', 'holding', 'circulating'],
    intentionAffinities: [
      'ding-settled-stability',
      'shou-steady-keeping',
      'qian-modest-restraint',
      'jie-measured-limitation',
      'zhong-centered-measure',
      'yang-patient-nourishment',
      'he-harmonizing-balance',
      'zhen-stable-constancy',
    ],
    strategicVectorAffinities: ['stabilize', 'nourish', 'repair', 'limit', 'simplify'],
    somaticVectorAffinities: ['ground', 'settle', 'maintain-rhythm'],
    macroAffinities: ['established'],
    scope: 'ordinary-work-domain',
    formalization: 'current',
    sourceLabel: CURRENT_FORMALIZATION_SOURCE,
    sourceUrls: TRADITIONAL_SOURCE_URLS,
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'metal-refinement-closure',
    category: 'metal',
    elementCharacter: '金',
    elementPinyin: 'Jīn',
    title: 'Refinement & Closure',
    spirit: {
      character: '魄',
      pinyin: 'Pò',
      classicalGloss: 'Corporeal soul',
      zangCorrespondence: 'lung',
    },
    description:
      'Editorial and evaluative work that sharpens standards, removes excess, and brings work to a clean handoff or close.',
    taskDomains: [
      'Editing and revision',
      'Quality assurance, testing, audit, and standards review',
      'Prioritization and scope reduction',
      'Completion, publishing, and handoff',
      'Filing, archiving, deprecation, and cleanup',
    ],
    relationAffinities: ['complete', 'contain', 'withdraw', 'transform'],
    directionAffinities: ['closing', 'releasing', 'inward', 'holding'],
    intentionAffinities: [
      'ding-settled-stability',
      'shou-steady-keeping',
      'qian-modest-restraint',
      'jie-measured-limitation',
      'ming-clear-discernment',
      'shou-gathering-inward',
      'xing-timely-execution',
    ],
    strategicVectorAffinities: ['clarify', 'complete', 'limit', 'simplify', 'release', 'gather'],
    somaticVectorAffinities: ['settle', 'ground', 'allow-space', 'reduce-pace'],
    macroAffinities: ['established'],
    scope: 'ordinary-work-domain',
    formalization: 'current',
    sourceLabel: CURRENT_FORMALIZATION_SOURCE,
    sourceUrls: TRADITIONAL_SOURCE_URLS,
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'water-insight-resolve',
    category: 'water',
    elementCharacter: '水',
    elementPinyin: 'Shuǐ',
    title: 'Insight & Resolve',
    spirit: {
      character: '志',
      pinyin: 'Zhì',
      classicalGloss: 'Will',
      zangCorrespondence: 'kidney',
    },
    description:
      'Depth-oriented work for intuitive synthesis, complex investigation, systems thinking, and long-horizon decisions.',
    taskDomains: [
      'Deep analysis and technical problem-solving',
      'Intuitive synthesis and sense-making',
      'Root-cause investigation and research',
      'Systems architecture and scenario modeling',
      'Reflective writing and decision incubation',
    ],
    relationAffinities: ['wait', 'withdraw', 'counterbalance', 'transform'],
    directionAffinities: ['inward', 'holding', 'stabilizing', 'circulating'],
    intentionAffinities: [
      'shou-steady-keeping',
      'jing-quiet-stillness',
      'zhen-stable-constancy',
      'yang-patient-nourishment',
      'ming-clear-discernment',
      'shou-gathering-inward',
      'zhong-centered-measure',
    ],
    strategicVectorAffinities: ['pause', 'gather', 'clarify', 'nourish', 'adapt'],
    somaticVectorAffinities: ['settle', 'allow-space', 'reduce-pace', 'soften'],
    macroAffinities: ['established'],
    scope: 'ordinary-work-domain',
    formalization: 'current',
    sourceLabel: CURRENT_FORMALIZATION_SOURCE,
    sourceUrls: TRADITIONAL_SOURCE_URLS,
    version: EXECUTION_LIBRARY_VERSION,
  },
])

// Preserve the public export used by the guidance engine while the output now contains domains.
export const EXECUTION_ACTION_LIBRARY = ELEMENTAL_EXECUTION_LIBRARY

export const getExecutionDefinition = (id: string) =>
  ELEMENTAL_EXECUTION_LIBRARY.find((definition) => definition.id === id)
