import type { ExecutionDefinition } from '../types'
import { EXECUTION_LIBRARY_VERSION } from '../synthesis/semanticVersion'

const followIntentions = [
  'sui-responsive-following',
  'rou-yielding-softness',
  'tong-unobstructed-passage',
  'he-harmonizing-balance',
  'zhen-stable-constancy',
  'xing-timely-execution',
] as const

const containIntentions = [
  'ding-settled-stability',
  'shou-steady-keeping',
  'qian-modest-restraint',
  'jie-measured-limitation',
  'zhong-centered-measure',
  'shou-gathering-inward',
] as const

const balanceIntentions = [
  'qian-modest-restraint',
  'rou-yielding-softness',
  'zhong-centered-measure',
  'tong-unobstructed-passage',
  'yang-patient-nourishment',
  'ming-clear-discernment',
  'he-harmonizing-balance',
] as const

const completionIntentions = [
  'ding-settled-stability',
  'jie-measured-limitation',
  'zhen-stable-constancy',
  'ming-clear-discernment',
  'shou-gathering-inward',
  'xing-timely-execution',
] as const

const waitIntentions = [
  'ding-settled-stability',
  'shou-steady-keeping',
  'jie-measured-limitation',
  'jing-quiet-stillness',
  'zhen-stable-constancy',
  'yang-patient-nourishment',
] as const

const transformIntentions = [
  'sui-responsive-following',
  'rou-yielding-softness',
  'zhong-centered-measure',
  'tong-unobstructed-passage',
  'yang-patient-nourishment',
  'ming-clear-discernment',
  'he-harmonizing-balance',
  'xing-timely-execution',
] as const

const withdrawIntentions = [
  'shou-steady-keeping',
  'qian-modest-restraint',
  'jing-quiet-stillness',
  'shou-gathering-inward',
] as const

export const EXECUTION_ACTION_LIBRARY: readonly ExecutionDefinition[] = Object.freeze([
  {
    id: 'task-continue-checkpoint',
    category: 'task',
    text: 'Continue one already-moving task until its next visible checkpoint.',
    observableEndpoint: 'The task reaches its next recorded checkpoint.',
    actionCount: 1,
    effortLevel: 'measured',
    compatibleRelations: ['follow'],
    compatibleDirections: ['forward', 'circulating'],
    compatibleIntentions: followIntentions,
    strategicVectors: ['advance', 'adapt'],
    somaticVectors: ['maintain-rhythm'],
    risk: 'low',
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'environment-prepare-next-tools',
    category: 'environment',
    text: 'Place the materials for one supported task within reach and begin only that task.',
    observableEndpoint: 'One task is open with only its required materials present.',
    actionCount: 2,
    effortLevel: 'measured',
    compatibleRelations: ['follow'],
    compatibleDirections: ['forward', 'circulating'],
    compatibleIntentions: followIntentions,
    strategicVectors: ['advance', 'simplify'],
    somaticVectors: ['ground'],
    risk: 'low',
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'task-close-optional-input',
    category: 'task',
    text: 'Close one optional input and leave the remaining list unchanged.',
    observableEndpoint: 'One optional input is closed and no replacement is added.',
    actionCount: 2,
    effortLevel: 'minimal',
    compatibleRelations: ['contain'],
    compatibleDirections: ['holding', 'stabilizing', 'inward'],
    compatibleIntentions: containIntentions,
    strategicVectors: ['limit', 'simplify'],
    somaticVectors: ['settle'],
    risk: 'low',
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'environment-clear-surface',
    category: 'environment',
    text: 'Clear one obstructed surface and return remaining items to place.',
    observableEndpoint: 'The chosen surface is usable and loose items are returned.',
    actionCount: 2,
    effortLevel: 'minimal',
    compatibleRelations: ['contain', 'transform', 'counterbalance'],
    compatibleDirections: ['holding', 'stabilizing', 'circulating'],
    compatibleIntentions: [...containIntentions, ...balanceIntentions, ...transformIntentions],
    strategicVectors: ['simplify', 'repair'],
    somaticVectors: ['ground'],
    risk: 'low',
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'task-add-missing-support',
    category: 'task',
    text: 'Add one missing support to the current task before continuing.',
    observableEndpoint: 'The named support is present in the current task.',
    actionCount: 1,
    effortLevel: 'measured',
    compatibleRelations: ['counterbalance'],
    compatibleDirections: ['stabilizing', 'circulating', 'forward'],
    compatibleIntentions: balanceIntentions,
    strategicVectors: ['stabilize', 'nourish'],
    somaticVectors: ['ground'],
    risk: 'low',
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'somatic-settle-pace',
    category: 'somatic',
    text: 'Reduce pace briefly and allow breathing to settle naturally.',
    observableEndpoint: 'Ordinary breathing and pace feel unforced before activity resumes.',
    actionCount: 2,
    effortLevel: 'minimal',
    compatibleRelations: ['counterbalance', 'contain', 'wait', 'withdraw', 'transform'],
    compatibleDirections: ['stabilizing', 'holding', 'inward', 'circulating'],
    compatibleIntentions: [
      ...balanceIntentions,
      ...containIntentions,
      ...waitIntentions,
      ...withdrawIntentions,
      ...transformIntentions,
    ],
    strategicVectors: ['stabilize', 'pause'],
    somaticVectors: ['reduce-pace', 'settle', 'soften'],
    risk: 'low',
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'task-finish-nearly-complete',
    category: 'task',
    text: 'Finish one nearly complete task before opening another.',
    observableEndpoint: 'One existing task is marked complete and no new task is opened.',
    actionCount: 1,
    effortLevel: 'steady',
    compatibleRelations: ['complete'],
    compatibleDirections: ['closing', 'releasing'],
    compatibleIntentions: completionIntentions,
    strategicVectors: ['complete', 'release'],
    somaticVectors: ['ground'],
    risk: 'low',
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'environment-close-completed-work',
    category: 'environment',
    text: 'Put away the completed materials and leave the workspace closed.',
    observableEndpoint: 'Completed materials are stored and the workspace is closed.',
    actionCount: 2,
    effortLevel: 'measured',
    compatibleRelations: ['complete', 'withdraw'],
    compatibleDirections: ['closing', 'releasing', 'inward'],
    compatibleIntentions: [...completionIntentions, ...withdrawIntentions],
    strategicVectors: ['complete', 'release', 'gather'],
    somaticVectors: ['settle'],
    risk: 'low',
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'pause-record-until-boundary',
    category: 'pause',
    text: 'Write the decision down and leave it untouched until the next boundary.',
    observableEndpoint: 'The decision is recorded and remains unchanged until the boundary.',
    actionCount: 2,
    effortLevel: 'minimal',
    compatibleRelations: ['wait'],
    compatibleDirections: ['holding', 'stabilizing', 'inward'],
    compatibleIntentions: waitIntentions,
    strategicVectors: ['pause', 'clarify'],
    somaticVectors: ['allow-space', 'settle'],
    risk: 'low',
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'pause-one-interval',
    category: 'pause',
    text: 'Leave one unresolved item unchanged until the current time block ends.',
    observableEndpoint: 'The item remains unchanged when the current time block ends.',
    actionCount: 1,
    effortLevel: 'minimal',
    compatibleRelations: ['wait', 'withdraw'],
    compatibleDirections: ['holding', 'inward'],
    compatibleIntentions: [...waitIntentions, ...withdrawIntentions],
    strategicVectors: ['pause', 'gather'],
    somaticVectors: ['allow-space'],
    risk: 'low',
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'task-repair-one-obstruction',
    category: 'task',
    text: 'Repair one small obstruction and stop when ordinary use is restored.',
    observableEndpoint: 'The selected item returns to ordinary use.',
    actionCount: 2,
    effortLevel: 'measured',
    compatibleRelations: ['transform'],
    compatibleDirections: ['circulating', 'stabilizing', 'forward'],
    compatibleIntentions: transformIntentions,
    strategicVectors: ['repair', 'simplify'],
    somaticVectors: ['restore-circulation'],
    risk: 'low',
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'environment-restore-path',
    category: 'environment',
    text: 'Remove one obstruction from a frequently used path and stop there.',
    observableEndpoint: 'The selected path is clear for ordinary use.',
    actionCount: 2,
    effortLevel: 'minimal',
    compatibleRelations: ['transform'],
    compatibleDirections: ['circulating', 'stabilizing'],
    compatibleIntentions: transformIntentions,
    strategicVectors: ['repair', 'simplify'],
    somaticVectors: ['restore-circulation', 'ground'],
    risk: 'low',
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'environment-silence-notification',
    category: 'environment',
    text: 'Silence one nonessential notification source until the next boundary.',
    observableEndpoint: 'One notification source remains silent until the boundary.',
    actionCount: 1,
    effortLevel: 'minimal',
    compatibleRelations: ['withdraw'],
    compatibleDirections: ['inward', 'releasing', 'holding'],
    compatibleIntentions: withdrawIntentions,
    strategicVectors: ['gather', 'release'],
    somaticVectors: ['allow-space', 'reduce-pace'],
    risk: 'low',
    version: EXECUTION_LIBRARY_VERSION,
  },
  {
    id: 'task-defer-external-request',
    category: 'task',
    text: 'Move one nonessential external request to the next available review boundary.',
    observableEndpoint: 'One request has a later review boundary and no immediate action.',
    actionCount: 1,
    effortLevel: 'minimal',
    compatibleRelations: ['withdraw'],
    compatibleDirections: ['inward', 'releasing'],
    compatibleIntentions: withdrawIntentions,
    strategicVectors: ['gather', 'pause'],
    somaticVectors: ['reduce-pace'],
    risk: 'low',
    version: EXECUTION_LIBRARY_VERSION,
  },
])

export const getExecutionDefinition = (id: string) =>
  EXECUTION_ACTION_LIBRARY.find((definition) => definition.id === id)
