CREATE CONSTRAINT alchemy_migration_id IF NOT EXISTS
FOR (n:AlchemyMigration) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT herb_material_id IF NOT EXISTS
FOR (n:HerbMaterial) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT botanical_taxon_id IF NOT EXISTS
FOR (n:BotanicalTaxon) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT medicinal_part_id IF NOT EXISTS
FOR (n:MedicinalPart) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT preparation_id IF NOT EXISTS
FOR (n:Preparation) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT formula_id IF NOT EXISTS
FOR (n:Formula) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT formula_variant_id IF NOT EXISTS
FOR (n:FormulaVariant) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT compound_id IF NOT EXISTS
FOR (n:Compound) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT action_id IF NOT EXISTS
FOR (n:Action) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT pattern_id IF NOT EXISTS
FOR (n:Pattern) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT symptom_term_id IF NOT EXISTS
FOR (n:SymptomTerm) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT channel_id IF NOT EXISTS
FOR (n:Channel) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT flavor_id IF NOT EXISTS
FOR (n:Flavor) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT thermal_nature_id IF NOT EXISTS
FOR (n:ThermalNature) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT category_id IF NOT EXISTS
FOR (n:Category) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT source_id IF NOT EXISTS
FOR (n:Source) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT claim_id IF NOT EXISTS
FOR (n:Claim) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT document_id IF NOT EXISTS
FOR (n:Document) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT passage_id IF NOT EXISTS
FOR (n:Passage) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT import_run_id IF NOT EXISTS
FOR (n:ImportRun) REQUIRE n.id IS UNIQUE;
