import type { IntentionDefinition } from '../types'
import { INTENTION_LEXICON_VERSION } from '../synthesis/semanticVersion'

export const INTENTION_LEXICON: readonly IntentionDefinition[] = Object.freeze([
  {
    id: 'ding-settled-stability',
    character: '定',
    pinyin: 'Dìng',
    englishLabel: 'Settled Stability',
    shortDefinition: 'Establish enough steadiness for the next proportionate movement.',
    compatibleRelations: ['contain', 'complete', 'wait'],
    compatibleDirections: ['holding', 'stabilizing', 'closing'],
    compatibleLunarModes: ['culminating', 'releasing', 'resting', 'threshold'],
    compatibleEffortLevels: ['minimal', 'measured', 'steady'],
    strategicVectors: ['stabilize', 'complete'],
    somaticVectors: ['settle', 'ground'],
    conflicts: ['xing-timely-execution'],
    version: INTENTION_LEXICON_VERSION,
  },
  {
    id: 'shou-steady-keeping',
    character: '守',
    pinyin: 'Shǒu',
    englishLabel: 'Steady Keeping',
    shortDefinition: 'Protect what remains sound without adding unnecessary reach.',
    compatibleRelations: ['contain', 'wait', 'withdraw'],
    compatibleDirections: ['holding', 'inward', 'stabilizing'],
    compatibleLunarModes: ['culminating', 'releasing', 'resting', 'threshold'],
    compatibleEffortLevels: ['minimal', 'measured', 'steady'],
    strategicVectors: ['stabilize', 'limit'],
    somaticVectors: ['ground', 'maintain-rhythm'],
    conflicts: ['xing-timely-execution'],
    version: INTENTION_LEXICON_VERSION,
  },
  {
    id: 'sui-responsive-following',
    character: '隨',
    pinyin: 'Suí',
    englishLabel: 'Responsive Following',
    shortDefinition: 'Move with support already present while remaining able to adjust.',
    compatibleRelations: ['follow', 'transform'],
    compatibleDirections: ['forward', 'circulating'],
    compatibleLunarModes: ['emerging', 'building', 'releasing'],
    compatibleEffortLevels: ['measured', 'steady'],
    strategicVectors: ['adapt', 'advance'],
    somaticVectors: ['maintain-rhythm', 'allow-space'],
    conflicts: ['jing-quiet-stillness'],
    version: INTENTION_LEXICON_VERSION,
  },
  {
    id: 'qian-modest-restraint',
    character: '謙',
    pinyin: 'Qiān',
    englishLabel: 'Modest Restraint',
    shortDefinition: 'Reduce excess and make room for the missing stabilizing quality.',
    compatibleRelations: ['contain', 'counterbalance', 'withdraw'],
    compatibleDirections: ['inward', 'holding', 'stabilizing'],
    compatibleLunarModes: ['building', 'culminating', 'releasing', 'resting'],
    compatibleEffortLevels: ['minimal', 'measured'],
    strategicVectors: ['limit', 'simplify'],
    somaticVectors: ['reduce-pace', 'ground'],
    conflicts: ['xing-timely-execution'],
    version: INTENTION_LEXICON_VERSION,
  },
  {
    id: 'rou-yielding-softness',
    character: '柔',
    pinyin: 'Róu',
    englishLabel: 'Yielding Softness',
    shortDefinition: 'Use flexibility to restore movement without escalating force.',
    compatibleRelations: ['counterbalance', 'follow', 'transform'],
    compatibleDirections: ['circulating', 'inward', 'stabilizing'],
    compatibleLunarModes: ['emerging', 'releasing', 'resting', 'threshold'],
    compatibleEffortLevels: ['minimal', 'measured'],
    strategicVectors: ['adapt', 'repair'],
    somaticVectors: ['soften', 'restore-circulation'],
    conflicts: ['xing-timely-execution'],
    version: INTENTION_LEXICON_VERSION,
  },
  {
    id: 'jie-measured-limitation',
    character: '節',
    pinyin: 'Jié',
    englishLabel: 'Measured Limitation',
    shortDefinition: 'Give movement a useful boundary and a clear point of enough.',
    compatibleRelations: ['contain', 'wait', 'complete'],
    compatibleDirections: ['holding', 'closing', 'stabilizing'],
    compatibleLunarModes: ['culminating', 'releasing', 'resting', 'threshold'],
    compatibleEffortLevels: ['minimal', 'measured', 'steady'],
    strategicVectors: ['limit', 'complete'],
    somaticVectors: ['ground', 'reduce-pace'],
    conflicts: ['tong-unobstructed-passage'],
    version: INTENTION_LEXICON_VERSION,
  },
  {
    id: 'zhong-centered-measure',
    character: '中',
    pinyin: 'Zhōng',
    englishLabel: 'Centered Measure',
    shortDefinition: 'Restore proportion by holding near the workable middle.',
    compatibleRelations: ['counterbalance', 'contain', 'transform'],
    compatibleDirections: ['stabilizing', 'circulating', 'holding'],
    compatibleLunarModes: [
      'emerging',
      'building',
      'culminating',
      'releasing',
      'resting',
      'threshold',
    ],
    compatibleEffortLevels: ['minimal', 'measured', 'steady'],
    strategicVectors: ['stabilize', 'clarify'],
    somaticVectors: ['ground', 'settle'],
    conflicts: [],
    version: INTENTION_LEXICON_VERSION,
  },
  {
    id: 'jing-quiet-stillness',
    character: '靜',
    pinyin: 'Jìng',
    englishLabel: 'Quiet Stillness',
    shortDefinition: 'Let unnecessary motion settle while the next boundary becomes clear.',
    compatibleRelations: ['wait', 'withdraw', 'contain'],
    compatibleDirections: ['holding', 'inward', 'stabilizing'],
    compatibleLunarModes: ['releasing', 'resting', 'threshold'],
    compatibleEffortLevels: ['minimal', 'measured'],
    strategicVectors: ['pause', 'gather'],
    somaticVectors: ['settle', 'allow-space'],
    conflicts: ['sui-responsive-following', 'xing-timely-execution'],
    version: INTENTION_LEXICON_VERSION,
  },
  {
    id: 'zhen-stable-constancy',
    character: '貞',
    pinyin: 'Zhēn',
    englishLabel: 'Stable Constancy',
    shortDefinition: 'Maintain the sound course until its present work is complete.',
    compatibleRelations: ['complete', 'follow', 'wait'],
    compatibleDirections: ['forward', 'stabilizing', 'holding', 'closing'],
    compatibleLunarModes: ['building', 'culminating', 'threshold'],
    compatibleEffortLevels: ['measured', 'steady'],
    strategicVectors: ['stabilize', 'complete'],
    somaticVectors: ['maintain-rhythm', 'ground'],
    conflicts: [],
    version: INTENTION_LEXICON_VERSION,
  },
  {
    id: 'tong-unobstructed-passage',
    character: '通',
    pinyin: 'Tōng',
    englishLabel: 'Unobstructed Passage',
    shortDefinition: 'Clear the smallest obstruction so useful movement can continue.',
    compatibleRelations: ['transform', 'follow', 'counterbalance'],
    compatibleDirections: ['circulating', 'forward'],
    compatibleLunarModes: ['emerging', 'building', 'releasing'],
    compatibleEffortLevels: ['measured', 'steady'],
    strategicVectors: ['repair', 'adapt'],
    somaticVectors: ['restore-circulation', 'maintain-rhythm'],
    conflicts: ['jie-measured-limitation'],
    version: INTENTION_LEXICON_VERSION,
  },
  {
    id: 'yang-patient-nourishment',
    character: '養',
    pinyin: 'Yǎng',
    englishLabel: 'Patient Nourishment',
    shortDefinition: 'Supply modest support and allow capacity to rebuild gradually.',
    compatibleRelations: ['counterbalance', 'wait', 'transform'],
    compatibleDirections: ['stabilizing', 'inward', 'circulating'],
    compatibleLunarModes: ['resting', 'emerging', 'building'],
    compatibleEffortLevels: ['minimal', 'measured', 'steady'],
    strategicVectors: ['nourish', 'stabilize'],
    somaticVectors: ['soften', 'ground'],
    conflicts: ['xing-timely-execution'],
    version: INTENTION_LEXICON_VERSION,
  },
  {
    id: 'ming-clear-discernment',
    character: '明',
    pinyin: 'Míng',
    englishLabel: 'Clear Discernment',
    shortDefinition: 'Distinguish the next useful step from avoidable complication.',
    compatibleRelations: ['counterbalance', 'complete', 'transform'],
    compatibleDirections: ['forward', 'stabilizing', 'closing'],
    compatibleLunarModes: ['emerging', 'building', 'culminating', 'releasing'],
    compatibleEffortLevels: ['measured', 'steady', 'decisive'],
    strategicVectors: ['clarify', 'simplify'],
    somaticVectors: ['allow-space', 'settle'],
    conflicts: [],
    version: INTENTION_LEXICON_VERSION,
  },
  {
    id: 'he-harmonizing-balance',
    character: '和',
    pinyin: 'Hé',
    englishLabel: 'Harmonizing Balance',
    shortDefinition: 'Bring competing movements into a workable shared proportion.',
    compatibleRelations: ['counterbalance', 'transform', 'follow'],
    compatibleDirections: ['stabilizing', 'circulating'],
    compatibleLunarModes: ['emerging', 'building', 'releasing', 'resting'],
    compatibleEffortLevels: ['measured', 'steady'],
    strategicVectors: ['stabilize', 'adapt'],
    somaticVectors: ['restore-circulation', 'soften'],
    conflicts: [],
    version: INTENTION_LEXICON_VERSION,
  },
  {
    id: 'shou-gathering-inward',
    character: '收',
    pinyin: 'Shōu',
    englishLabel: 'Gathering Inward',
    shortDefinition: 'Collect attention and resources after outward work has ripened.',
    compatibleRelations: ['withdraw', 'complete', 'contain'],
    compatibleDirections: ['inward', 'releasing', 'closing'],
    compatibleLunarModes: ['culminating', 'releasing', 'resting'],
    compatibleEffortLevels: ['minimal', 'measured', 'steady'],
    strategicVectors: ['gather', 'release'],
    somaticVectors: ['reduce-pace', 'settle'],
    conflicts: ['xing-timely-execution'],
    version: INTENTION_LEXICON_VERSION,
  },
  {
    id: 'xing-timely-execution',
    character: '行',
    pinyin: 'Xíng',
    englishLabel: 'Timely Execution',
    shortDefinition: 'Carry the supported movement through its visible next boundary.',
    compatibleRelations: ['follow', 'complete', 'transform'],
    compatibleDirections: ['forward', 'closing', 'circulating'],
    compatibleLunarModes: ['emerging', 'building', 'culminating'],
    compatibleEffortLevels: ['measured', 'steady', 'decisive'],
    strategicVectors: ['advance', 'complete'],
    somaticVectors: ['maintain-rhythm', 'ground'],
    conflicts: [
      'ding-settled-stability',
      'shou-steady-keeping',
      'qian-modest-restraint',
      'rou-yielding-softness',
      'jing-quiet-stillness',
      'yang-patient-nourishment',
      'shou-gathering-inward',
    ],
    version: INTENTION_LEXICON_VERSION,
  },
])

export const getIntentionDefinition = (id: string) =>
  INTENTION_LEXICON.find((definition) => definition.id === id)
