import type { HexagramSemanticProfile, SemanticProfileReview } from '../types'
import { HEXAGRAM_SEMANTIC_PROFILE_VERSION } from '../versions'

const SPEC_REVIEW: SemanticProfileReview = Object.freeze({
  status: 'spec-reviewed',
  authoredBy: 'Current Flow Semantic Layer v1',
  reviewedBy: [],
  reviewBasis: 'Temporal Semantic Resolver v1 product specification',
})

const profile = (
  value: Omit<HexagramSemanticProfile, 'version' | 'review'>,
): HexagramSemanticProfile =>
  Object.freeze({
    ...value,
    version: HEXAGRAM_SEMANTIC_PROFILE_VERSION,
    review: SPEC_REVIEW,
  })

export const HEXAGRAM_SEMANTIC_PROFILES: readonly HexagramSemanticProfile[] = Object.freeze([
  profile({
    hexagramNumber: 1,
    movement: ['emerge', 'rise', 'expand'],
    strategicVectors: ['begin', 'continue', 'clarify'],
    responseRelations: ['follow'],
    compatibleEffortLevels: ['measured', 'steady', 'decisive'],
    supportedTextures: ['clear', 'fire'],
    compatibleLunarModes: ['emergence', 'accumulation'],
    imageFamilies: ['weather', 'movement'],
    compatibleIntentionIds: [
      'xing-timely-execution',
      'sui-responsive-following',
      'tong-unobstructed-passage',
    ],
    preferredVerbs: ['begin', 'continue', 'develop'],
    forbiddenVerbs: ['withdraw', 'abandon'],
    notes: ['Current operational profile for supported initiation and continuation.'],
  }),
  profile({
    hexagramNumber: 2,
    movement: ['gather', 'store', 'return'],
    strategicVectors: ['receive', 'protect', 'organize'],
    responseRelations: ['counterbalance', 'follow', 'wait'],
    compatibleEffortLevels: ['minimal', 'measured', 'steady'],
    supportedTextures: ['damp', 'cold', 'clear'],
    compatibleLunarModes: ['accumulation', 'consolidation', 'concealment'],
    imageFamilies: ['terrain', 'vessel'],
    compatibleIntentionIds: [
      'rou-yielding-softness',
      'yang-patient-nourishment',
      'he-harmonizing-balance',
      'shou-steady-keeping',
    ],
    preferredVerbs: ['receive', 'support', 'hold'],
    forbiddenVerbs: ['force', 'dominate'],
    notes: ['Current operational profile for receptive support and consolidation.'],
  }),
  profile({
    hexagramNumber: 12,
    movement: ['contract', 'store'],
    strategicVectors: ['pause', 'protect', 'narrow', 'withdraw'],
    responseRelations: ['withdraw', 'wait', 'contain'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['dry', 'cold', 'mixed'],
    compatibleLunarModes: ['consolidation', 'concealment'],
    imageFamilies: ['architecture', 'terrain'],
    compatibleIntentionIds: [
      'jing-quiet-stillness',
      'shou-steady-keeping',
      'jie-measured-limitation',
      'qian-modest-restraint',
    ],
    preferredVerbs: ['pause', 'protect', 'withdraw', 'limit'],
    forbiddenVerbs: ['expand', 'accelerate', 'force'],
    notes: ['Current operational profile for contraction and protected waiting.'],
  }),
  profile({
    hexagramNumber: 18,
    movement: ['turn', 'return'],
    strategicVectors: ['repair', 'organize', 'clarify'],
    responseRelations: ['transform', 'complete'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['damp', 'mixed'],
    compatibleLunarModes: ['distribution', 'consolidation'],
    imageFamilies: ['architecture', 'plant'],
    compatibleIntentionIds: [
      'ming-clear-discernment',
      'tong-unobstructed-passage',
      'zhong-centered-measure',
      'rou-yielding-softness',
    ],
    preferredVerbs: ['repair', 'clear', 'restore', 'organize'],
    forbiddenVerbs: ['ignore', 'cover', 'accelerate'],
    notes: ['Current operational profile for bounded repair and restoration.'],
  }),
  profile({
    hexagramNumber: 28,
    movement: ['culminate', 'turn'],
    strategicVectors: ['finish', 'repair', 'narrow', 'release'],
    responseRelations: ['contain', 'complete'],
    compatibleEffortLevels: ['measured'],
    supportedTextures: ['damp', 'mixed'],
    compatibleLunarModes: ['culmination', 'distribution'],
    imageFamilies: ['architecture', 'vessel'],
    compatibleIntentionIds: [
      'jie-measured-limitation',
      'ding-settled-stability',
      'shou-gathering-inward',
      'ming-clear-discernment',
    ],
    preferredVerbs: ['complete', 'reduce', 'redistribute'],
    forbiddenVerbs: ['expand', 'accelerate'],
    notes: [
      "The specification's “reduce” strategy is represented by the controlled “narrow” vector; “reduce” remains an approved verb.",
    ],
  }),
  profile({
    hexagramNumber: 48,
    movement: ['return', 'store', 'rise'],
    strategicVectors: ['receive', 'repair', 'organize', 'continue'],
    responseRelations: ['transform', 'counterbalance', 'follow'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['cold', 'clear'],
    compatibleLunarModes: ['consolidation', 'emergence'],
    imageFamilies: ['water', 'architecture', 'vessel'],
    compatibleIntentionIds: [
      'tong-unobstructed-passage',
      'yang-patient-nourishment',
      'zhen-stable-constancy',
      'zhong-centered-measure',
    ],
    preferredVerbs: ['restore', 'draw', 'maintain', 'share'],
    forbiddenVerbs: ['deplete', 'contaminate', 'abandon'],
    notes: ['Current operational profile for maintained access and restoration.'],
  }),
  profile({
    hexagramNumber: 52,
    movement: ['store', 'contract'],
    strategicVectors: ['pause', 'protect', 'narrow'],
    responseRelations: ['wait', 'contain', 'withdraw'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['cold', 'dry', 'clear'],
    compatibleLunarModes: ['consolidation', 'concealment'],
    imageFamilies: ['terrain', 'architecture'],
    compatibleIntentionIds: [
      'jing-quiet-stillness',
      'ding-settled-stability',
      'shou-steady-keeping',
      'jie-measured-limitation',
    ],
    preferredVerbs: ['stop', 'settle', 'hold', 'protect'],
    forbiddenVerbs: ['rush', 'expand', 'scatter'],
    notes: ['Current operational profile for stillness and boundary retention.'],
  }),
  profile({
    hexagramNumber: 53,
    movement: ['emerge', 'rise'],
    strategicVectors: ['begin', 'continue', 'organize', 'adapt'],
    responseRelations: ['follow', 'wait'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['wind', 'clear'],
    compatibleLunarModes: ['emergence', 'accumulation'],
    imageFamilies: ['plant', 'movement', 'terrain'],
    compatibleIntentionIds: [
      'zhen-stable-constancy',
      'sui-responsive-following',
      'yang-patient-nourishment',
    ],
    preferredVerbs: ['develop', 'continue', 'sequence', 'adapt'],
    forbiddenVerbs: ['rush', 'leap', 'force'],
    notes: ['Current operational profile for gradual emergence and sequencing.'],
  }),
  profile({
    hexagramNumber: 57,
    movement: ['emerge', 'turn', 'return'],
    strategicVectors: ['adapt', 'clarify', 'continue'],
    responseRelations: ['follow', 'transform'],
    compatibleEffortLevels: ['measured'],
    supportedTextures: ['wind', 'clear'],
    compatibleLunarModes: ['emergence', 'distribution'],
    imageFamilies: ['weather', 'plant', 'movement'],
    compatibleIntentionIds: [
      'sui-responsive-following',
      'rou-yielding-softness',
      'ming-clear-discernment',
      'tong-unobstructed-passage',
    ],
    preferredVerbs: ['enter', 'adapt', 'clarify', 'continue'],
    forbiddenVerbs: ['force', 'strike', 'harden'],
    notes: ['Current operational profile for adaptive entry and clarification.'],
  }),
  profile({
    hexagramNumber: 61,
    movement: ['gather', 'return'],
    strategicVectors: ['clarify', 'receive', 'protect'],
    responseRelations: ['counterbalance', 'follow', 'wait'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['clear', 'mixed'],
    compatibleLunarModes: ['consolidation', 'emergence'],
    imageFamilies: ['vessel', 'water'],
    compatibleIntentionIds: [
      'ming-clear-discernment',
      'zhong-centered-measure',
      'he-harmonizing-balance',
      'rou-yielding-softness',
    ],
    preferredVerbs: ['clarify', 'receive', 'listen', 'verify'],
    forbiddenVerbs: ['perform', 'exaggerate', 'force'],
    notes: ['Current operational profile for clarification and receptive verification.'],
  }),
  profile({
    hexagramNumber: 62,
    movement: ['descend', 'turn', 'rise'],
    strategicVectors: ['narrow', 'protect', 'organize', 'finish'],
    responseRelations: ['contain', 'wait'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['wind', 'dry', 'mixed'],
    compatibleLunarModes: ['culmination', 'distribution'],
    imageFamilies: ['movement', 'terrain'],
    compatibleIntentionIds: [
      'jie-measured-limitation',
      'qian-modest-restraint',
      'shou-steady-keeping',
      'ding-settled-stability',
    ],
    preferredVerbs: ['narrow', 'attend', 'reduce', 'complete'],
    forbiddenVerbs: ['expand', 'overreach', 'accelerate'],
    notes: ['Current operational profile for small-scale completion and restraint.'],
  }),
  profile({
    hexagramNumber: 63,
    movement: ['culminate', 'descend', 'store'],
    strategicVectors: ['finish', 'protect', 'organize', 'release'],
    responseRelations: ['complete', 'contain', 'withdraw'],
    compatibleEffortLevels: ['measured'],
    supportedTextures: ['fire', 'mixed'],
    compatibleLunarModes: ['culmination', 'consolidation'],
    imageFamilies: ['water', 'vessel', 'architecture'],
    compatibleIntentionIds: [
      'ding-settled-stability',
      'jie-measured-limitation',
      'shou-gathering-inward',
      'zhen-stable-constancy',
    ],
    preferredVerbs: ['complete', 'secure', 'close', 'release'],
    forbiddenVerbs: ['reopen', 'expand', 'neglect'],
    notes: ['Current operational profile for completion and secured closure.'],
  }),
  profile({
    hexagramNumber: 64,
    movement: ['rise', 'turn', 'emerge'],
    strategicVectors: ['clarify', 'organize', 'adapt', 'pause'],
    responseRelations: ['transform', 'wait', 'follow'],
    compatibleEffortLevels: ['measured'],
    supportedTextures: ['fire', 'mixed'],
    compatibleLunarModes: ['emergence', 'accumulation'],
    imageFamilies: ['water', 'movement', 'vessel'],
    compatibleIntentionIds: [
      'ming-clear-discernment',
      'sui-responsive-following',
      'zhong-centered-measure',
      'tong-unobstructed-passage',
    ],
    preferredVerbs: ['prepare', 'clarify', 'adapt', 'sequence'],
    forbiddenVerbs: ['rush', 'declare', 'force'],
    notes: ['Current operational profile for transition before completion.'],
  }),
])
