import type { HexagramSemanticProfile, SemanticProfileReview } from '../types'
import { HEXAGRAM_SEMANTIC_PROFILE_VERSION } from '../versions'

const SPEC_REVIEW: SemanticProfileReview = Object.freeze({
  status: 'spec-reviewed',
  authoredBy: 'Current Flow Semantic Layer v1',
  reviewedBy: [],
  reviewBasis: 'Current Temporal Semantic Resolver v1 product-formalization specification',
})

const profile = (
  value: Omit<HexagramSemanticProfile, 'version' | 'review'>,
): HexagramSemanticProfile =>
  Object.freeze({
    ...value,
    version: HEXAGRAM_SEMANTIC_PROFILE_VERSION,
    review: SPEC_REVIEW,
  })

export const HEXAGRAM_SEMANTIC_PROFILES: readonly HexagramSemanticProfile[] = Object.freeze([
  profile({
    hexagramNumber: 1,
    movement: ['emerge', 'rise', 'expand'],
    strategicVectors: ['begin', 'continue', 'clarify'],
    responseRelations: ['follow'],
    compatibleEffortLevels: ['measured', 'steady', 'decisive'],
    supportedTextures: ['clear', 'fire'],
    compatibleLunarModes: ['emergence', 'accumulation'],
    imageFamilies: ['weather', 'movement'],
    compatibleIntentionIds: [
      'xing-timely-execution',
      'sui-responsive-following',
      'tong-unobstructed-passage',
    ],
    preferredVerbs: ['begin', 'continue', 'develop'],
    forbiddenVerbs: ['withdraw', 'abandon'],
    notes: ['Current operational profile for supported initiation and continuation.'],
  }),
  profile({
    hexagramNumber: 2,
    movement: ['gather', 'store', 'return'],
    strategicVectors: ['receive', 'protect', 'organize'],
    responseRelations: ['counterbalance', 'follow', 'wait'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['damp', 'cold', 'clear'],
    compatibleLunarModes: ['consolidation', 'accumulation', 'concealment'],
    imageFamilies: ['terrain', 'vessel'],
    compatibleIntentionIds: [
      'rou-yielding-softness',
      'yang-patient-nourishment',
      'he-harmonizing-balance',
      'zhong-centered-measure',
    ],
    preferredVerbs: ['receive', 'support', 'hold'],
    forbiddenVerbs: ['force', 'dominate'],
    notes: ['Current operational profile for receptive support and consolidation.'],
  }),
  profile({
    hexagramNumber: 3,
    movement: ['emerge', 'gather', 'turn'],
    strategicVectors: ['begin', 'organize', 'pause', 'adapt'],
    responseRelations: ['wait', 'transform', 'follow'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['damp', 'mixed', 'cold'],
    compatibleLunarModes: ['concealment', 'accumulation', 'emergence'],
    imageFamilies: ['water', 'plant', 'movement'],
    compatibleIntentionIds: [
      'zhen-stable-constancy',
      'jing-quiet-stillness',
      'shou-steady-keeping',
      'ding-settled-stability',
    ],
    preferredVerbs: ['prepare', 'sequence', 'organize', 'wait'],
    forbiddenVerbs: ['force', 'rush', 'scatter'],
    notes: ['Current operational profile for organizing a difficult beginning without forcing it.'],
  }),
  profile({
    hexagramNumber: 4,
    movement: ['gather', 'emerge', 'store'],
    strategicVectors: ['receive', 'clarify', 'organize', 'begin'],
    responseRelations: ['counterbalance', 'wait', 'transform'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['damp', 'cold', 'clear'],
    compatibleLunarModes: ['accumulation', 'concealment'],
    imageFamilies: ['water', 'terrain', 'vessel'],
    compatibleIntentionIds: [
      'yang-patient-nourishment',
      'ming-clear-discernment',
      'qian-modest-restraint',
      'tong-unobstructed-passage',
    ],
    preferredVerbs: ['inquire', 'learn', 'organize', 'receive'],
    forbiddenVerbs: ['presume', 'perform', 'rush'],
    notes: ['Current operational profile for disciplined learning and supported clarification.'],
  }),
  profile({
    hexagramNumber: 5,
    movement: ['store', 'gather', 'rise'],
    strategicVectors: ['pause', 'protect', 'receive', 'continue'],
    responseRelations: ['wait', 'contain'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['cold', 'damp', 'clear'],
    compatibleLunarModes: ['concealment', 'accumulation'],
    imageFamilies: ['water', 'weather', 'vessel'],
    compatibleIntentionIds: [
      'jing-quiet-stillness',
      'zhen-stable-constancy',
      'shou-steady-keeping',
      'ding-settled-stability',
    ],
    preferredVerbs: ['wait', 'prepare', 'nourish', 'observe'],
    forbiddenVerbs: ['rush', 'force', 'commit'],
    notes: ['Current operational profile for prepared waiting and conserved capacity.'],
  }),
  profile({
    hexagramNumber: 6,
    movement: ['contract', 'turn', 'gather'],
    strategicVectors: ['clarify', 'narrow', 'withdraw', 'pause'],
    responseRelations: ['withdraw', 'contain', 'wait'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['dry', 'mixed', 'cold'],
    compatibleLunarModes: ['distribution', 'consolidation'],
    imageFamilies: ['architecture', 'movement', 'water'],
    compatibleIntentionIds: [
      'qian-modest-restraint',
      'jing-quiet-stillness',
      'shou-steady-keeping',
      'shou-gathering-inward',
    ],
    preferredVerbs: ['mediate', 'clarify', 'limit', 'withdraw'],
    forbiddenVerbs: ['escalate', 'accuse', 'force'],
    notes: [
      'Current operational profile for de-escalation, clear boundaries, and timely withdrawal.',
    ],
  }),
  profile({
    hexagramNumber: 7,
    movement: ['gather', 'store', 'rise'],
    strategicVectors: ['organize', 'protect', 'continue', 'narrow'],
    responseRelations: ['contain', 'follow'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['cold', 'mixed', 'dry'],
    compatibleLunarModes: ['consolidation', 'accumulation'],
    imageFamilies: ['terrain', 'architecture', 'movement'],
    compatibleIntentionIds: [
      'shou-steady-keeping',
      'qian-modest-restraint',
      'jing-quiet-stillness',
      'shou-gathering-inward',
    ],
    preferredVerbs: ['coordinate', 'assign', 'discipline', 'protect'],
    forbiddenVerbs: ['scatter', 'dominate', 'improvise'],
    notes: ['Current operational profile for organized responsibility in service of a shared aim.'],
  }),
  profile({
    hexagramNumber: 8,
    movement: ['gather', 'return', 'rise'],
    strategicVectors: ['receive', 'organize', 'continue', 'clarify'],
    responseRelations: ['follow', 'counterbalance'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['damp', 'clear', 'cold'],
    compatibleLunarModes: ['emergence', 'accumulation'],
    imageFamilies: ['water', 'vessel', 'movement'],
    compatibleIntentionIds: [
      'he-harmonizing-balance',
      'sui-responsive-following',
      'tong-unobstructed-passage',
      'rou-yielding-softness',
    ],
    preferredVerbs: ['join', 'align', 'contribute', 'verify'],
    forbiddenVerbs: ['isolate', 'coerce', 'cling'],
    notes: ['Current operational profile for sincere affiliation around a durable center.'],
  }),
  profile({
    hexagramNumber: 9,
    movement: ['store', 'rise', 'gather'],
    strategicVectors: ['narrow', 'organize', 'continue', 'protect'],
    responseRelations: ['contain', 'wait'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['wind', 'clear', 'dry'],
    compatibleLunarModes: ['consolidation', 'accumulation'],
    imageFamilies: ['weather', 'plant', 'architecture'],
    compatibleIntentionIds: [
      'qian-modest-restraint',
      'shou-steady-keeping',
      'jie-measured-limitation',
      'zhong-centered-measure',
    ],
    preferredVerbs: ['refine', 'repeat', 'prepare', 'contain'],
    forbiddenVerbs: ['force', 'overreach', 'rush'],
    notes: ['Current operational profile for patient refinement through modest repeated action.'],
  }),
  profile({
    hexagramNumber: 10,
    movement: ['rise', 'turn', 'store'],
    strategicVectors: ['continue', 'adapt', 'clarify', 'narrow'],
    responseRelations: ['follow', 'contain'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['clear', 'fire', 'dry'],
    compatibleLunarModes: ['emergence', 'accumulation'],
    imageFamilies: ['movement', 'terrain', 'weather'],
    compatibleIntentionIds: [
      'sui-responsive-following',
      'tong-unobstructed-passage',
      'rou-yielding-softness',
      'he-harmonizing-balance',
    ],
    preferredVerbs: ['proceed', 'attend', 'adjust', 'respect'],
    forbiddenVerbs: ['provoke', 'rush', 'trample'],
    notes: ['Current operational profile for alert, courteous movement through sensitive ground.'],
  }),
  profile({
    hexagramNumber: 11,
    movement: ['rise', 'expand', 'return'],
    strategicVectors: ['continue', 'receive', 'organize', 'release'],
    responseRelations: ['follow', 'counterbalance'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['clear', 'damp', 'wind'],
    compatibleLunarModes: ['accumulation', 'emergence'],
    imageFamilies: ['terrain', 'weather', 'movement'],
    compatibleIntentionIds: [
      'sui-responsive-following',
      'zhen-stable-constancy',
      'tong-unobstructed-passage',
      'xing-timely-execution',
    ],
    preferredVerbs: ['exchange', 'circulate', 'steward', 'continue'],
    forbiddenVerbs: ['hoard', 'force', 'neglect'],
    notes: ['Current operational profile for balanced exchange and continued stewardship.'],
  }),
  profile({
    hexagramNumber: 12,
    movement: ['contract', 'store'],
    strategicVectors: ['pause', 'protect', 'narrow', 'withdraw'],
    responseRelations: ['withdraw', 'wait', 'contain'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['dry', 'cold', 'mixed'],
    compatibleLunarModes: ['consolidation', 'concealment'],
    imageFamilies: ['architecture', 'terrain'],
    compatibleIntentionIds: [
      'jing-quiet-stillness',
      'shou-steady-keeping',
      'jie-measured-limitation',
      'qian-modest-restraint',
    ],
    preferredVerbs: ['pause', 'protect', 'withdraw', 'limit'],
    forbiddenVerbs: ['expand', 'accelerate', 'force'],
    notes: ['Current operational profile for contraction and protected waiting.'],
  }),
  profile({
    hexagramNumber: 13,
    movement: ['gather', 'rise', 'expand'],
    strategicVectors: ['clarify', 'organize', 'continue', 'receive'],
    responseRelations: ['follow', 'counterbalance'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['fire', 'clear', 'mixed'],
    compatibleLunarModes: ['emergence', 'accumulation'],
    imageFamilies: ['movement', 'vessel', 'architecture'],
    compatibleIntentionIds: [
      'sui-responsive-following',
      'tong-unobstructed-passage',
      'xing-timely-execution',
      'rou-yielding-softness',
    ],
    preferredVerbs: ['cooperate', 'distinguish', 'convene', 'contribute'],
    forbiddenVerbs: ['conform', 'exclude', 'blur'],
    notes: ['Current operational profile for principled cooperation without erasing difference.'],
  }),
  profile({
    hexagramNumber: 14,
    movement: ['culminate', 'gather', 'store'],
    strategicVectors: ['organize', 'protect', 'release', 'narrow'],
    responseRelations: ['contain', 'complete'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['fire', 'clear', 'heat'],
    compatibleLunarModes: ['culmination', 'distribution'],
    imageFamilies: ['vessel', 'architecture', 'weather'],
    compatibleIntentionIds: [
      'qian-modest-restraint',
      'jie-measured-limitation',
      'ding-settled-stability',
      'shou-gathering-inward',
    ],
    preferredVerbs: ['steward', 'share', 'allocate', 'secure'],
    forbiddenVerbs: ['hoard', 'squander', 'display'],
    notes: ['Current operational profile for proportionate stewardship at a point of abundance.'],
  }),
  profile({
    hexagramNumber: 15,
    movement: ['descend', 'store', 'return'],
    strategicVectors: ['narrow', 'release', 'organize', 'receive'],
    responseRelations: ['counterbalance', 'contain'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['clear', 'damp', 'cold'],
    compatibleLunarModes: ['consolidation', 'distribution'],
    imageFamilies: ['terrain', 'vessel', 'movement'],
    compatibleIntentionIds: [
      'qian-modest-restraint',
      'rou-yielding-softness',
      'zhong-centered-measure',
      'yang-patient-nourishment',
    ],
    preferredVerbs: ['reduce', 'balance', 'yield', 'redistribute'],
    forbiddenVerbs: ['boast', 'inflate', 'dominate'],
    notes: ['Current operational profile for reducing excess and restoring proportion.'],
  }),
  profile({
    hexagramNumber: 16,
    movement: ['rise', 'expand', 'turn'],
    strategicVectors: ['begin', 'continue', 'organize', 'adapt'],
    responseRelations: ['follow', 'contain'],
    compatibleEffortLevels: ['measured', 'steady', 'decisive'],
    supportedTextures: ['heat', 'fire', 'mixed'],
    compatibleLunarModes: ['emergence', 'accumulation'],
    imageFamilies: ['weather', 'movement', 'vessel'],
    compatibleIntentionIds: [
      'xing-timely-execution',
      'sui-responsive-following',
      'tong-unobstructed-passage',
    ],
    preferredVerbs: ['mobilize', 'rehearse', 'coordinate', 'begin'],
    forbiddenVerbs: ['hype', 'rush', 'scatter'],
    notes: [
      'Current operational profile for enthusiasm disciplined by readiness and shared rhythm.',
    ],
  }),
  profile({
    hexagramNumber: 17,
    movement: ['turn', 'return', 'rise'],
    strategicVectors: ['adapt', 'continue', 'receive', 'clarify'],
    responseRelations: ['follow', 'transform'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['damp', 'wind', 'clear'],
    compatibleLunarModes: ['distribution', 'emergence'],
    imageFamilies: ['movement', 'water', 'weather'],
    compatibleIntentionIds: [
      'sui-responsive-following',
      'rou-yielding-softness',
      'he-harmonizing-balance',
      'tong-unobstructed-passage',
    ],
    preferredVerbs: ['follow', 'adjust', 'listen', 'continue'],
    forbiddenVerbs: ['imitate', 'submit', 'force'],
    notes: ['Current operational profile for responsive allegiance without loss of integrity.'],
  }),
  profile({
    hexagramNumber: 18,
    movement: ['turn', 'return'],
    strategicVectors: ['repair', 'organize', 'clarify'],
    responseRelations: ['transform', 'complete'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['damp', 'mixed'],
    compatibleLunarModes: ['distribution', 'consolidation'],
    imageFamilies: ['architecture', 'plant'],
    compatibleIntentionIds: [
      'ming-clear-discernment',
      'tong-unobstructed-passage',
      'zhong-centered-measure',
      'rou-yielding-softness',
    ],
    preferredVerbs: ['repair', 'clear', 'restore', 'organize'],
    forbiddenVerbs: ['ignore', 'cover', 'accelerate'],
    notes: ['Current operational profile for bounded repair and restoration.'],
  }),
  profile({
    hexagramNumber: 19,
    movement: ['rise', 'emerge', 'expand'],
    strategicVectors: ['begin', 'continue', 'receive', 'organize'],
    responseRelations: ['follow', 'counterbalance'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['damp', 'clear', 'heat'],
    compatibleLunarModes: ['emergence', 'accumulation'],
    imageFamilies: ['terrain', 'water', 'movement'],
    compatibleIntentionIds: [
      'xing-timely-execution',
      'sui-responsive-following',
      'tong-unobstructed-passage',
    ],
    preferredVerbs: ['approach', 'welcome', 'prepare', 'teach'],
    forbiddenVerbs: ['overwhelm', 'delay', 'assume'],
    notes: ['Current operational profile for generous approach joined to practical foresight.'],
  }),
  profile({
    hexagramNumber: 20,
    movement: ['gather', 'store', 'return'],
    strategicVectors: ['pause', 'clarify', 'receive', 'organize'],
    responseRelations: ['wait', 'counterbalance'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['wind', 'clear', 'cold'],
    compatibleLunarModes: ['consolidation', 'concealment'],
    imageFamilies: ['weather', 'terrain', 'architecture'],
    compatibleIntentionIds: [
      'jing-quiet-stillness',
      'ding-settled-stability',
      'yang-patient-nourishment',
      'shou-steady-keeping',
    ],
    preferredVerbs: ['observe', 'reflect', 'clarify', 'witness'],
    forbiddenVerbs: ['perform', 'interfere', 'rush'],
    notes: ['Current operational profile for contemplation that clarifies conduct and influence.'],
  }),
  profile({
    hexagramNumber: 21,
    movement: ['turn', 'rise', 'culminate'],
    strategicVectors: ['clarify', 'narrow', 'repair', 'finish'],
    responseRelations: ['transform', 'complete'],
    compatibleEffortLevels: ['steady', 'decisive'],
    supportedTextures: ['fire', 'dry', 'heat'],
    compatibleLunarModes: ['culmination', 'distribution'],
    imageFamilies: ['architecture', 'movement', 'vessel'],
    compatibleIntentionIds: [
      'ming-clear-discernment',
      'zhong-centered-measure',
      'xing-timely-execution',
    ],
    preferredVerbs: ['decide', 'clarify', 'separate', 'resolve'],
    forbiddenVerbs: ['equivocate', 'overpunish', 'ignore'],
    notes: ['Current operational profile for precise judgment that restores workable order.'],
  }),
  profile({
    hexagramNumber: 22,
    movement: ['store', 'emerge', 'culminate'],
    strategicVectors: ['clarify', 'narrow', 'organize', 'finish'],
    responseRelations: ['contain', 'complete'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['fire', 'clear', 'dry'],
    compatibleLunarModes: ['culmination', 'distribution'],
    imageFamilies: ['architecture', 'vessel', 'plant'],
    compatibleIntentionIds: [
      'qian-modest-restraint',
      'zhong-centered-measure',
      'jie-measured-limitation',
      'ding-settled-stability',
    ],
    preferredVerbs: ['refine', 'frame', 'reveal', 'finish'],
    forbiddenVerbs: ['obscure', 'inflate', 'distract'],
    notes: ['Current operational profile for form that reveals rather than replaces meaning.'],
  }),
  profile({
    hexagramNumber: 23,
    movement: ['descend', 'contract', 'gather'],
    strategicVectors: ['withdraw', 'protect', 'narrow', 'release'],
    responseRelations: ['withdraw', 'contain'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['dry', 'cold', 'mixed'],
    compatibleLunarModes: ['distribution', 'concealment'],
    imageFamilies: ['terrain', 'architecture', 'movement'],
    compatibleIntentionIds: [
      'shou-steady-keeping',
      'qian-modest-restraint',
      'jing-quiet-stillness',
      'shou-gathering-inward',
    ],
    preferredVerbs: ['shed', 'protect', 'withdraw', 'simplify'],
    forbiddenVerbs: ['rebuild', 'cling', 'expand'],
    notes: ['Current operational profile for protecting the essential through a season of loss.'],
  }),
  profile({
    hexagramNumber: 24,
    movement: ['return', 'emerge', 'rise'],
    strategicVectors: ['begin', 'continue', 'adapt', 'clarify'],
    responseRelations: ['follow', 'transform'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['cold', 'clear', 'wind'],
    compatibleLunarModes: ['emergence', 'accumulation'],
    imageFamilies: ['movement', 'plant', 'terrain'],
    compatibleIntentionIds: [
      'sui-responsive-following',
      'rou-yielding-softness',
      'tong-unobstructed-passage',
      'xing-timely-execution',
    ],
    preferredVerbs: ['return', 'resume', 'begin', 'reorient'],
    forbiddenVerbs: ['rush', 'overcorrect', 'abandon'],
    notes: ['Current operational profile for quiet renewal through repeated return.'],
  }),
  profile({
    hexagramNumber: 25,
    movement: ['emerge', 'rise', 'turn'],
    strategicVectors: ['begin', 'continue', 'clarify', 'adapt'],
    responseRelations: ['follow', 'transform'],
    compatibleEffortLevels: ['measured', 'steady', 'decisive'],
    supportedTextures: ['clear', 'wind', 'fire'],
    compatibleLunarModes: ['emergence', 'accumulation'],
    imageFamilies: ['weather', 'movement', 'terrain'],
    compatibleIntentionIds: [
      'sui-responsive-following',
      'tong-unobstructed-passage',
      'xing-timely-execution',
    ],
    preferredVerbs: ['respond', 'act', 'verify', 'continue'],
    forbiddenVerbs: ['scheme', 'prejudge', 'force'],
    notes: [
      'Current operational profile for direct action responsive to what is actually present.',
    ],
  }),
  profile({
    hexagramNumber: 26,
    movement: ['store', 'gather', 'rise'],
    strategicVectors: ['protect', 'organize', 'continue', 'pause'],
    responseRelations: ['contain', 'wait'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['clear', 'dry', 'cold'],
    compatibleLunarModes: ['consolidation', 'accumulation'],
    imageFamilies: ['terrain', 'architecture', 'vessel'],
    compatibleIntentionIds: [
      'ding-settled-stability',
      'shou-steady-keeping',
      'qian-modest-restraint',
      'jie-measured-limitation',
    ],
    preferredVerbs: ['train', 'store', 'prepare', 'restrain'],
    forbiddenVerbs: ['discharge', 'boast', 'force'],
    notes: [
      'Current operational profile for cultivated strength held ready for consequential use.',
    ],
  }),
  profile({
    hexagramNumber: 27,
    movement: ['gather', 'store', 'return'],
    strategicVectors: ['receive', 'clarify', 'organize', 'protect'],
    responseRelations: ['counterbalance', 'contain'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['damp', 'cold', 'clear'],
    compatibleLunarModes: ['accumulation', 'consolidation'],
    imageFamilies: ['vessel', 'plant', 'water'],
    compatibleIntentionIds: [
      'yang-patient-nourishment',
      'ming-clear-discernment',
      'zhong-centered-measure',
      'qian-modest-restraint',
    ],
    preferredVerbs: ['nourish', 'select', 'receive', 'offer'],
    forbiddenVerbs: ['deplete', 'overfill', 'pollute'],
    notes: ['Current operational profile for discernment in what is taken in and given out.'],
  }),
  profile({
    hexagramNumber: 28,
    movement: ['culminate', 'turn'],
    strategicVectors: ['finish', 'repair', 'narrow', 'release'],
    responseRelations: ['contain', 'complete'],
    compatibleEffortLevels: ['measured'],
    supportedTextures: ['damp', 'mixed'],
    compatibleLunarModes: ['culmination', 'distribution'],
    imageFamilies: ['architecture', 'vessel'],
    compatibleIntentionIds: [
      'jie-measured-limitation',
      'ding-settled-stability',
      'shou-gathering-inward',
      'ming-clear-discernment',
    ],
    preferredVerbs: ['complete', 'reduce', 'redistribute'],
    forbiddenVerbs: ['expand', 'accelerate'],
    notes: [
      'Current operational profile for measured action under structural overload.',
      "The specification's “reduce” strategy is represented by the controlled “narrow” vector; “reduce” remains an approved verb.",
    ],
  }),
  profile({
    hexagramNumber: 29,
    movement: ['descend', 'return', 'store'],
    strategicVectors: ['protect', 'continue', 'clarify', 'pause'],
    responseRelations: ['wait', 'contain'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['cold', 'damp', 'mixed'],
    compatibleLunarModes: ['concealment', 'consolidation'],
    imageFamilies: ['water', 'movement', 'terrain'],
    compatibleIntentionIds: [
      'ding-settled-stability',
      'jie-measured-limitation',
      'zhen-stable-constancy',
    ],
    preferredVerbs: ['proceed', 'verify', 'anchor', 'repeat'],
    forbiddenVerbs: ['plunge', 'panic', 'force'],
    notes: ['Current operational profile for steady continuity through repeated uncertainty.'],
  }),
  profile({
    hexagramNumber: 30,
    movement: ['rise', 'expand', 'culminate'],
    strategicVectors: ['clarify', 'continue', 'organize', 'protect'],
    responseRelations: ['follow', 'contain'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['fire', 'heat', 'clear'],
    compatibleLunarModes: ['accumulation', 'culmination'],
    imageFamilies: ['weather', 'vessel', 'movement'],
    compatibleIntentionIds: [
      'zhen-stable-constancy',
      'tong-unobstructed-passage',
      'xing-timely-execution',
      'sui-responsive-following',
    ],
    preferredVerbs: ['illuminate', 'sustain', 'distinguish', 'continue'],
    forbiddenVerbs: ['scorch', 'fixate', 'consume'],
    notes: ['Current operational profile for lucid attention sustained by worthy commitments.'],
  }),
  profile({
    hexagramNumber: 31,
    movement: ['turn', 'gather', 'rise'],
    strategicVectors: ['receive', 'adapt', 'clarify', 'continue'],
    responseRelations: ['follow', 'counterbalance'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['damp', 'wind', 'clear'],
    compatibleLunarModes: ['emergence', 'distribution'],
    imageFamilies: ['movement', 'water', 'terrain'],
    compatibleIntentionIds: [
      'he-harmonizing-balance',
      'rou-yielding-softness',
      'sui-responsive-following',
      'tong-unobstructed-passage',
    ],
    preferredVerbs: ['invite', 'listen', 'respond', 'adjust'],
    forbiddenVerbs: ['manipulate', 'pressure', 'perform'],
    notes: ['Current operational profile for responsive connection grounded in mutual respect.'],
  }),
  profile({
    hexagramNumber: 32,
    movement: ['rise', 'return', 'store'],
    strategicVectors: ['continue', 'organize', 'adapt', 'protect'],
    responseRelations: ['follow', 'complete'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['wind', 'clear', 'damp'],
    compatibleLunarModes: ['accumulation', 'consolidation'],
    imageFamilies: ['plant', 'movement', 'weather'],
    compatibleIntentionIds: [
      'zhen-stable-constancy',
      'sui-responsive-following',
      'he-harmonizing-balance',
      'xing-timely-execution',
    ],
    preferredVerbs: ['sustain', 'repeat', 'adjust', 'maintain'],
    forbiddenVerbs: ['drift', 'abandon', 'rigidify'],
    notes: ['Current operational profile for enduring orientation with adaptable expression.'],
  }),
  profile({
    hexagramNumber: 33,
    movement: ['contract', 'gather', 'descend'],
    strategicVectors: ['withdraw', 'protect', 'narrow', 'pause'],
    responseRelations: ['withdraw', 'wait'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['dry', 'cold', 'clear'],
    compatibleLunarModes: ['distribution', 'consolidation'],
    imageFamilies: ['terrain', 'architecture', 'movement'],
    compatibleIntentionIds: [
      'shou-steady-keeping',
      'shou-gathering-inward',
      'qian-modest-restraint',
      'jing-quiet-stillness',
    ],
    preferredVerbs: ['retreat', 'conserve', 'disengage', 'protect'],
    forbiddenVerbs: ['pursue', 'provoke', 'broadcast'],
    notes: ['Current operational profile for distance that preserves dignity and future agency.'],
  }),
  profile({
    hexagramNumber: 34,
    movement: ['rise', 'culminate', 'store'],
    strategicVectors: ['narrow', 'protect', 'organize', 'release'],
    responseRelations: ['contain', 'complete'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['heat', 'fire', 'clear'],
    compatibleLunarModes: ['culmination', 'distribution'],
    imageFamilies: ['weather', 'movement', 'terrain'],
    compatibleIntentionIds: [
      'jie-measured-limitation',
      'ding-settled-stability',
      'shou-gathering-inward',
    ],
    preferredVerbs: ['channel', 'restrain', 'apply', 'finish'],
    forbiddenVerbs: ['overpower', 'accelerate', 'display'],
    notes: ['Current operational profile for strength governed by restraint and clear purpose.'],
  }),
  profile({
    hexagramNumber: 35,
    movement: ['rise', 'emerge', 'expand'],
    strategicVectors: ['continue', 'clarify', 'organize', 'begin'],
    responseRelations: ['follow', 'complete'],
    compatibleEffortLevels: ['measured', 'steady', 'decisive'],
    supportedTextures: ['fire', 'heat', 'clear'],
    compatibleLunarModes: ['accumulation', 'emergence'],
    imageFamilies: ['weather', 'movement', 'terrain'],
    compatibleIntentionIds: [
      'xing-timely-execution',
      'sui-responsive-following',
      'tong-unobstructed-passage',
      'zhen-stable-constancy',
    ],
    preferredVerbs: ['advance', 'contribute', 'clarify', 'continue'],
    forbiddenVerbs: ['grandstand', 'rush', 'force'],
    notes: [
      'Current operational profile for visible contribution that supports continued progress.',
    ],
  }),
  profile({
    hexagramNumber: 36,
    movement: ['descend', 'gather', 'store'],
    strategicVectors: ['protect', 'withdraw', 'narrow', 'clarify'],
    responseRelations: ['withdraw', 'contain'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['cold', 'mixed', 'dry'],
    compatibleLunarModes: ['consolidation', 'concealment'],
    imageFamilies: ['terrain', 'architecture', 'vessel'],
    compatibleIntentionIds: [
      'shou-steady-keeping',
      'qian-modest-restraint',
      'jing-quiet-stillness',
      'shou-gathering-inward',
    ],
    preferredVerbs: ['conceal', 'protect', 'conserve', 'withdraw'],
    forbiddenVerbs: ['expose', 'confront', 'broadcast'],
    notes: ['Current operational profile for protective discretion without loss of principle.'],
  }),
  profile({
    hexagramNumber: 37,
    movement: ['gather', 'store', 'return'],
    strategicVectors: ['organize', 'protect', 'continue', 'clarify'],
    responseRelations: ['contain', 'follow'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['fire', 'wind', 'clear'],
    compatibleLunarModes: ['consolidation', 'accumulation'],
    imageFamilies: ['architecture', 'vessel', 'plant'],
    compatibleIntentionIds: [
      'shou-steady-keeping',
      'zhong-centered-measure',
      'ding-settled-stability',
      'qian-modest-restraint',
    ],
    preferredVerbs: ['tend', 'coordinate', 'model', 'maintain'],
    forbiddenVerbs: ['control', 'neglect', 'triangulate'],
    notes: ['Current operational profile for dependable conduct that makes trust inhabitable.'],
  }),
  profile({
    hexagramNumber: 38,
    movement: ['turn', 'contract', 'return'],
    strategicVectors: ['clarify', 'adapt', 'narrow', 'receive'],
    responseRelations: ['counterbalance', 'transform'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['fire', 'dry', 'mixed'],
    compatibleLunarModes: ['distribution', 'consolidation'],
    imageFamilies: ['movement', 'water', 'vessel'],
    compatibleIntentionIds: [
      'zhong-centered-measure',
      'he-harmonizing-balance',
      'rou-yielding-softness',
      'qian-modest-restraint',
    ],
    preferredVerbs: ['distinguish', 'negotiate', 'compare', 'align'],
    forbiddenVerbs: ['homogenize', 'polarize', 'force'],
    notes: [
      'Current operational profile for small agreements and clear distinctions within plurality.',
    ],
  }),
  profile({
    hexagramNumber: 39,
    movement: ['contract', 'turn', 'gather'],
    strategicVectors: ['adapt', 'pause', 'clarify', 'withdraw'],
    responseRelations: ['transform', 'wait'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['cold', 'damp', 'mixed'],
    compatibleLunarModes: ['consolidation', 'concealment'],
    imageFamilies: ['terrain', 'water', 'movement'],
    compatibleIntentionIds: [
      'rou-yielding-softness',
      'zhong-centered-measure',
      'yang-patient-nourishment',
      'he-harmonizing-balance',
    ],
    preferredVerbs: ['reroute', 'consult', 'pause', 'adjust'],
    forbiddenVerbs: ['push', 'blame', 'repeat'],
    notes: [
      'Current operational profile for changing direction when the present route is obstructed.',
    ],
  }),
  profile({
    hexagramNumber: 40,
    movement: ['turn', 'descend', 'return'],
    strategicVectors: ['release', 'finish', 'repair', 'clarify'],
    responseRelations: ['complete', 'transform'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['damp', 'wind', 'clear'],
    compatibleLunarModes: ['distribution', 'consolidation'],
    imageFamilies: ['water', 'movement', 'weather'],
    compatibleIntentionIds: [
      'ding-settled-stability',
      'jie-measured-limitation',
      'ming-clear-discernment',
      'shou-gathering-inward',
    ],
    preferredVerbs: ['release', 'forgive', 'simplify', 'finish'],
    forbiddenVerbs: ['reopen', 'retain', 'punish'],
    notes: ['Current operational profile for prompt release and return to ordinary work.'],
  }),
  profile({
    hexagramNumber: 41,
    movement: ['gather', 'contract', 'store'],
    strategicVectors: ['narrow', 'release', 'protect', 'organize'],
    responseRelations: ['contain', 'withdraw'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['dry', 'clear', 'cold'],
    compatibleLunarModes: ['distribution', 'consolidation'],
    imageFamilies: ['terrain', 'vessel', 'architecture'],
    compatibleIntentionIds: [
      'qian-modest-restraint',
      'jie-measured-limitation',
      'shou-gathering-inward',
      'zhong-centered-measure',
    ],
    preferredVerbs: ['reduce', 'simplify', 'offer', 'protect'],
    forbiddenVerbs: ['strip', 'deplete', 'hoard'],
    notes: ['Current operational profile for sincere simplification that strengthens the whole.'],
  }),
  profile({
    hexagramNumber: 42,
    movement: ['rise', 'return', 'expand'],
    strategicVectors: ['receive', 'repair', 'continue', 'organize'],
    responseRelations: ['counterbalance', 'follow'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['wind', 'damp', 'clear'],
    compatibleLunarModes: ['accumulation', 'emergence'],
    imageFamilies: ['plant', 'movement', 'weather'],
    compatibleIntentionIds: [
      'yang-patient-nourishment',
      'ming-clear-discernment',
      'he-harmonizing-balance',
      'tong-unobstructed-passage',
    ],
    preferredVerbs: ['improve', 'supply', 'share', 'correct'],
    forbiddenVerbs: ['inflate', 'overload', 'waste'],
    notes: ['Current operational profile for generous improvement joined to correction.'],
  }),
  profile({
    hexagramNumber: 43,
    movement: ['culminate', 'rise', 'turn'],
    strategicVectors: ['clarify', 'finish', 'release', 'protect'],
    responseRelations: ['complete', 'transform'],
    compatibleEffortLevels: ['steady', 'decisive'],
    supportedTextures: ['heat', 'fire', 'clear'],
    compatibleLunarModes: ['culmination', 'distribution'],
    imageFamilies: ['weather', 'movement', 'architecture'],
    compatibleIntentionIds: [
      'ming-clear-discernment',
      'xing-timely-execution',
      'jie-measured-limitation',
      'ding-settled-stability',
    ],
    preferredVerbs: ['declare', 'resolve', 'separate', 'complete'],
    forbiddenVerbs: ['hesitate', 'escalate', 'attack'],
    notes: [
      'Current operational profile for firm disclosure supported by preparation and restraint.',
    ],
  }),
  profile({
    hexagramNumber: 44,
    movement: ['emerge', 'contract', 'turn'],
    strategicVectors: ['clarify', 'narrow', 'protect', 'pause'],
    responseRelations: ['contain', 'wait'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['wind', 'heat', 'mixed'],
    compatibleLunarModes: ['consolidation', 'concealment'],
    imageFamilies: ['weather', 'movement', 'architecture'],
    compatibleIntentionIds: [
      'shou-steady-keeping',
      'qian-modest-restraint',
      'zhong-centered-measure',
      'jing-quiet-stillness',
    ],
    preferredVerbs: ['notice', 'limit', 'verify', 'contain'],
    forbiddenVerbs: ['merge', 'indulge', 'ignore'],
    notes: ['Current operational profile for early recognition and proportionate boundaries.'],
  }),
  profile({
    hexagramNumber: 45,
    movement: ['gather', 'rise', 'return'],
    strategicVectors: ['organize', 'receive', 'continue', 'protect'],
    responseRelations: ['follow', 'contain'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['damp', 'cold', 'mixed'],
    compatibleLunarModes: ['accumulation', 'emergence'],
    imageFamilies: ['vessel', 'water', 'architecture'],
    compatibleIntentionIds: [
      'sui-responsive-following',
      'zhen-stable-constancy',
      'tong-unobstructed-passage',
      'xing-timely-execution',
    ],
    preferredVerbs: ['gather', 'convene', 'align', 'prepare'],
    forbiddenVerbs: ['crowd', 'coerce', 'scatter'],
    notes: ['Current operational profile for shared commitment supported by foresight.'],
  }),
  profile({
    hexagramNumber: 46,
    movement: ['rise', 'emerge', 'expand'],
    strategicVectors: ['continue', 'organize', 'adapt', 'begin'],
    responseRelations: ['follow', 'wait'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['wind', 'damp', 'clear'],
    compatibleLunarModes: ['accumulation', 'emergence'],
    imageFamilies: ['plant', 'terrain', 'movement'],
    compatibleIntentionIds: [
      'zhen-stable-constancy',
      'sui-responsive-following',
      'xing-timely-execution',
      'tong-unobstructed-passage',
    ],
    preferredVerbs: ['advance', 'cultivate', 'ask', 'continue'],
    forbiddenVerbs: ['leap', 'force', 'skip'],
    notes: ['Current operational profile for patient advance aided by trustworthy support.'],
  }),
  profile({
    hexagramNumber: 47,
    movement: ['contract', 'gather', 'store'],
    strategicVectors: ['pause', 'protect', 'narrow', 'clarify'],
    responseRelations: ['wait', 'withdraw'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['dry', 'cold', 'mixed'],
    compatibleLunarModes: ['concealment', 'consolidation'],
    imageFamilies: ['water', 'vessel', 'architecture'],
    compatibleIntentionIds: [
      'jing-quiet-stillness',
      'shou-steady-keeping',
      'ding-settled-stability',
      'jie-measured-limitation',
    ],
    preferredVerbs: ['endure', 'conserve', 'clarify', 'wait'],
    forbiddenVerbs: ['exhaust', 'perform', 'force'],
    notes: ['Current operational profile for inward steadiness under restricted circumstances.'],
  }),
  profile({
    hexagramNumber: 48,
    movement: ['return', 'store', 'rise'],
    strategicVectors: ['receive', 'repair', 'organize', 'continue'],
    responseRelations: ['transform', 'counterbalance', 'follow'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['cold', 'clear'],
    compatibleLunarModes: ['emergence', 'consolidation'],
    imageFamilies: ['water', 'architecture', 'vessel'],
    compatibleIntentionIds: [
      'tong-unobstructed-passage',
      'yang-patient-nourishment',
      'zhen-stable-constancy',
      'zhong-centered-measure',
    ],
    preferredVerbs: ['restore', 'draw', 'maintain', 'share'],
    forbiddenVerbs: ['deplete', 'contaminate', 'abandon'],
    notes: ['Current operational profile for maintained access and restoration.'],
  }),
  profile({
    hexagramNumber: 49,
    movement: ['turn', 'culminate', 'emerge'],
    strategicVectors: ['repair', 'release', 'clarify', 'begin'],
    responseRelations: ['transform', 'complete'],
    compatibleEffortLevels: ['steady', 'decisive'],
    supportedTextures: ['fire', 'heat', 'mixed'],
    compatibleLunarModes: ['culmination', 'distribution'],
    imageFamilies: ['movement', 'vessel', 'weather'],
    compatibleIntentionIds: [
      'ming-clear-discernment',
      'xing-timely-execution',
      'zhong-centered-measure',
    ],
    preferredVerbs: ['renew', 'replace', 'announce', 'begin'],
    forbiddenVerbs: ['improvise', 'conceal', 'delay'],
    notes: ['Current operational profile for decisive renewal made credible through preparation.'],
  }),
  profile({
    hexagramNumber: 50,
    movement: ['gather', 'store', 'rise'],
    strategicVectors: ['repair', 'organize', 'receive', 'continue'],
    responseRelations: ['transform', 'counterbalance'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['fire', 'damp', 'mixed'],
    compatibleLunarModes: ['consolidation', 'accumulation'],
    imageFamilies: ['vessel', 'plant', 'architecture'],
    compatibleIntentionIds: [
      'yang-patient-nourishment',
      'he-harmonizing-balance',
      'zhong-centered-measure',
      'rou-yielding-softness',
    ],
    preferredVerbs: ['refine', 'combine', 'transform', 'serve'],
    forbiddenVerbs: ['contaminate', 'waste', 'display'],
    notes: ['Current operational profile for refinement and service through transformation.'],
  }),
  profile({
    hexagramNumber: 51,
    movement: ['emerge', 'turn', 'rise'],
    strategicVectors: ['clarify', 'organize', 'pause', 'continue'],
    responseRelations: ['counterbalance', 'transform'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['heat', 'fire', 'mixed'],
    compatibleLunarModes: ['emergence', 'distribution'],
    imageFamilies: ['weather', 'movement', 'terrain'],
    compatibleIntentionIds: [
      'zhong-centered-measure',
      'he-harmonizing-balance',
      'rou-yielding-softness',
      'ming-clear-discernment',
    ],
    preferredVerbs: ['orient', 'steady', 'check', 'resume'],
    forbiddenVerbs: ['panic', 'react', 'scatter'],
    notes: ['Current operational profile for composure that learns from sudden movement.'],
  }),
  profile({
    hexagramNumber: 52,
    movement: ['store', 'contract'],
    strategicVectors: ['pause', 'protect', 'narrow'],
    responseRelations: ['wait', 'contain', 'withdraw'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['cold', 'dry', 'clear'],
    compatibleLunarModes: ['consolidation', 'concealment'],
    imageFamilies: ['terrain', 'architecture'],
    compatibleIntentionIds: [
      'jing-quiet-stillness',
      'ding-settled-stability',
      'shou-steady-keeping',
      'jie-measured-limitation',
    ],
    preferredVerbs: ['stop', 'settle', 'hold', 'protect'],
    forbiddenVerbs: ['rush', 'expand', 'scatter'],
    notes: ['Current operational profile for stillness and boundary retention.'],
  }),
  profile({
    hexagramNumber: 53,
    movement: ['emerge', 'rise'],
    strategicVectors: ['begin', 'continue', 'organize', 'adapt'],
    responseRelations: ['follow', 'wait'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['wind', 'clear'],
    compatibleLunarModes: ['accumulation', 'emergence'],
    imageFamilies: ['plant', 'movement', 'terrain'],
    compatibleIntentionIds: [
      'zhen-stable-constancy',
      'sui-responsive-following',
      'tong-unobstructed-passage',
      'xing-timely-execution',
    ],
    preferredVerbs: ['develop', 'continue', 'sequence', 'adapt'],
    forbiddenVerbs: ['rush', 'leap', 'force'],
    notes: ['Current operational profile for gradual emergence and sequencing.'],
  }),
  profile({
    hexagramNumber: 54,
    movement: ['turn', 'gather', 'descend'],
    strategicVectors: ['adapt', 'narrow', 'clarify', 'receive'],
    responseRelations: ['counterbalance', 'contain'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['damp', 'mixed', 'cold'],
    compatibleLunarModes: ['distribution', 'consolidation'],
    imageFamilies: ['movement', 'vessel', 'water'],
    compatibleIntentionIds: [
      'qian-modest-restraint',
      'rou-yielding-softness',
      'zhong-centered-measure',
    ],
    preferredVerbs: ['adapt', 'negotiate', 'accept', 'clarify'],
    forbiddenVerbs: ['assume', 'control', 'overpromise'],
    notes: ['Current operational profile for clear-eyed adaptation where control is limited.'],
  }),
  profile({
    hexagramNumber: 55,
    movement: ['culminate', 'expand', 'descend'],
    strategicVectors: ['finish', 'release', 'clarify', 'organize'],
    responseRelations: ['complete', 'contain'],
    compatibleEffortLevels: ['steady', 'decisive'],
    supportedTextures: ['fire', 'heat', 'clear'],
    compatibleLunarModes: ['culmination', 'distribution'],
    imageFamilies: ['weather', 'vessel', 'movement'],
    compatibleIntentionIds: [
      'xing-timely-execution',
      'ming-clear-discernment',
      'ding-settled-stability',
      'jie-measured-limitation',
    ],
    preferredVerbs: ['decide', 'distribute', 'complete', 'release'],
    forbiddenVerbs: ['hoard', 'delay', 'multiply'],
    notes: ['Current operational profile for decisive stewardship of a brief illuminated moment.'],
  }),
  profile({
    hexagramNumber: 56,
    movement: ['rise', 'turn', 'gather'],
    strategicVectors: ['adapt', 'narrow', 'clarify', 'continue'],
    responseRelations: ['follow', 'withdraw'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['fire', 'dry', 'clear'],
    compatibleLunarModes: ['distribution', 'emergence'],
    imageFamilies: ['movement', 'terrain', 'weather'],
    compatibleIntentionIds: [
      'rou-yielding-softness',
      'sui-responsive-following',
      'tong-unobstructed-passage',
      'he-harmonizing-balance',
    ],
    preferredVerbs: ['travel', 'adapt', 'observe', 'depart'],
    forbiddenVerbs: ['overstay', 'claim', 'burden'],
    notes: ['Current operational profile for modesty, clarity, and lightness in transit.'],
  }),
  profile({
    hexagramNumber: 57,
    movement: ['emerge', 'turn', 'return'],
    strategicVectors: ['adapt', 'clarify', 'continue'],
    responseRelations: ['follow', 'transform'],
    compatibleEffortLevels: ['measured'],
    supportedTextures: ['wind', 'clear'],
    compatibleLunarModes: ['emergence', 'distribution'],
    imageFamilies: ['weather', 'plant', 'movement'],
    compatibleIntentionIds: [
      'sui-responsive-following',
      'rou-yielding-softness',
      'ming-clear-discernment',
      'tong-unobstructed-passage',
    ],
    preferredVerbs: ['enter', 'adapt', 'clarify', 'continue'],
    forbiddenVerbs: ['force', 'strike', 'harden'],
    notes: ['Current operational profile for adaptive entry and clarification.'],
  }),
  profile({
    hexagramNumber: 58,
    movement: ['expand', 'return', 'gather'],
    strategicVectors: ['receive', 'clarify', 'continue', 'adapt'],
    responseRelations: ['follow', 'counterbalance'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['damp', 'clear', 'wind'],
    compatibleLunarModes: ['distribution', 'emergence'],
    imageFamilies: ['water', 'vessel', 'movement'],
    compatibleIntentionIds: [
      'he-harmonizing-balance',
      'sui-responsive-following',
      'rou-yielding-softness',
      'tong-unobstructed-passage',
    ],
    preferredVerbs: ['exchange', 'delight', 'listen', 'encourage'],
    forbiddenVerbs: ['flatter', 'distract', 'overpromise'],
    notes: ['Current operational profile for sincere dialogue that renews participation.'],
  }),
  profile({
    hexagramNumber: 59,
    movement: ['expand', 'turn', 'return'],
    strategicVectors: ['release', 'repair', 'adapt', 'clarify'],
    responseRelations: ['transform', 'follow'],
    compatibleEffortLevels: ['measured', 'steady'],
    supportedTextures: ['wind', 'damp', 'cold'],
    compatibleLunarModes: ['distribution', 'emergence'],
    imageFamilies: ['water', 'weather', 'movement'],
    compatibleIntentionIds: [
      'tong-unobstructed-passage',
      'rou-yielding-softness',
      'he-harmonizing-balance',
      'sui-responsive-following',
    ],
    preferredVerbs: ['dissolve', 'reconnect', 'circulate', 'release'],
    forbiddenVerbs: ['isolate', 'solidify', 'cling'],
    notes: ['Current operational profile for dissolving separation and restoring flow.'],
  }),
  profile({
    hexagramNumber: 60,
    movement: ['contract', 'store', 'turn'],
    strategicVectors: ['narrow', 'organize', 'protect', 'clarify'],
    responseRelations: ['contain', 'wait'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['cold', 'dry', 'clear'],
    compatibleLunarModes: ['consolidation', 'concealment'],
    imageFamilies: ['architecture', 'vessel', 'water'],
    compatibleIntentionIds: [
      'jie-measured-limitation',
      'qian-modest-restraint',
      'zhong-centered-measure',
      'ding-settled-stability',
    ],
    preferredVerbs: ['limit', 'measure', 'schedule', 'define'],
    forbiddenVerbs: ['rigidify', 'overregulate', 'scatter'],
    notes: ['Current operational profile for proportionate boundaries that sustain freedom.'],
  }),
  profile({
    hexagramNumber: 61,
    movement: ['gather', 'return'],
    strategicVectors: ['clarify', 'receive', 'protect'],
    responseRelations: ['counterbalance', 'follow', 'wait'],
    compatibleEffortLevels: ['measured'],
    supportedTextures: ['clear', 'mixed'],
    compatibleLunarModes: ['consolidation', 'emergence'],
    imageFamilies: ['vessel', 'water'],
    compatibleIntentionIds: [
      'ming-clear-discernment',
      'zhong-centered-measure',
      'he-harmonizing-balance',
      'rou-yielding-softness',
    ],
    preferredVerbs: ['clarify', 'receive', 'listen', 'verify'],
    forbiddenVerbs: ['perform', 'exaggerate', 'force'],
    notes: ['Current operational profile for clarification and receptive verification.'],
  }),
  profile({
    hexagramNumber: 62,
    movement: ['descend', 'turn', 'rise'],
    strategicVectors: ['narrow', 'protect', 'organize', 'finish'],
    responseRelations: ['contain', 'wait'],
    compatibleEffortLevels: ['minimal', 'measured'],
    supportedTextures: ['wind', 'dry', 'mixed'],
    compatibleLunarModes: ['culmination', 'distribution'],
    imageFamilies: ['movement', 'terrain'],
    compatibleIntentionIds: [
      'jie-measured-limitation',
      'qian-modest-restraint',
      'shou-steady-keeping',
      'ding-settled-stability',
      'shou-gathering-inward',
    ],
    preferredVerbs: ['narrow', 'attend', 'reduce', 'complete'],
    forbiddenVerbs: ['expand', 'overreach', 'accelerate'],
    notes: ['Current operational profile for small-scale completion and restraint.'],
  }),
  profile({
    hexagramNumber: 63,
    movement: ['culminate', 'descend', 'store'],
    strategicVectors: ['finish', 'protect', 'organize', 'release'],
    responseRelations: ['complete', 'contain', 'withdraw'],
    compatibleEffortLevels: ['measured'],
    supportedTextures: ['fire', 'mixed'],
    compatibleLunarModes: ['culmination', 'consolidation'],
    imageFamilies: ['water', 'vessel', 'architecture'],
    compatibleIntentionIds: [
      'ding-settled-stability',
      'jie-measured-limitation',
      'shou-gathering-inward',
      'zhen-stable-constancy',
    ],
    preferredVerbs: ['complete', 'secure', 'close', 'release'],
    forbiddenVerbs: ['reopen', 'expand', 'neglect'],
    notes: ['Current operational profile for completion and secured closure.'],
  }),
  profile({
    hexagramNumber: 64,
    movement: ['rise', 'turn', 'emerge'],
    strategicVectors: ['clarify', 'organize', 'adapt', 'pause'],
    responseRelations: ['transform', 'wait', 'follow'],
    compatibleEffortLevels: ['measured'],
    supportedTextures: ['fire', 'mixed'],
    compatibleLunarModes: ['emergence', 'accumulation'],
    imageFamilies: ['water', 'movement', 'vessel'],
    compatibleIntentionIds: [
      'ming-clear-discernment',
      'sui-responsive-following',
      'zhong-centered-measure',
      'tong-unobstructed-passage',
    ],
    preferredVerbs: ['prepare', 'clarify', 'adapt', 'sequence'],
    forbiddenVerbs: ['rush', 'declare', 'force'],
    notes: ['Current operational profile for transition before completion.'],
  }),
])
