import type { TransformationDefinition } from './types'

const structuralSourceIds = ['docs:YIJING_TRANSFORMATIONS', 'current:canonical-hexagram-registry']

export const TRANSFORMATION_DEFINITIONS = [
  {
    id: 'line-change',
    nameEnglish: 'Relating / Changed Hexagram',
    nameChinese: '變卦',
    aliases: ['changed hexagram', 'relating hexagram'],
    family: 'line-change',
    transformationClass: 'contextual',
    requirement: 'moving-lines',
    provenance: {
      tradition: 'Classical structural',
      sourceIds: structuralSourceIds,
      canonicality: 'widely-attested',
    },
    explanation: 'Changes only the user-selected lines, counted from the bottom.',
    implementationStatus: 'available',
    resultKind: 'single-hexagram',
  },
  {
    id: 'nuclear',
    nameEnglish: 'Nuclear / Mutual Hexagram',
    nameChinese: '互卦',
    aliases: ['mutual hexagram', 'inner hexagram'],
    family: 'interior',
    transformationClass: 'intrinsic',
    requirement: 'hexagram-only',
    provenance: {
      tradition: 'Classical structural',
      sourceIds: structuralSourceIds,
      canonicality: 'widely-attested',
    },
    explanation: 'Lines 2–4 form the lower trigram and lines 3–5 form the upper.',
    implementationStatus: 'available',
    resultKind: 'single-hexagram',
  },
  {
    id: 'line-complement',
    nameEnglish: 'Opposite / Line Complement',
    nameChinese: '錯卦',
    aliases: ['opposite', 'complement', 'pangtong'],
    family: 'core',
    transformationClass: 'intrinsic',
    requirement: 'hexagram-only',
    provenance: {
      tradition: 'Classical structural',
      sourceIds: structuralSourceIds,
      canonicality: 'widely-attested',
    },
    explanation: 'Changes every yin line to yang and every yang line to yin.',
    implementationStatus: 'available',
    resultKind: 'single-hexagram',
  },
  {
    id: 'line-reversal',
    nameEnglish: 'Reversed / Turned Hexagram',
    nameChinese: '綜卦',
    aliases: ['reverse', 'turned hexagram'],
    family: 'core',
    transformationClass: 'intrinsic',
    requirement: 'hexagram-only',
    provenance: {
      tradition: 'Classical structural',
      sourceIds: structuralSourceIds,
      canonicality: 'widely-attested',
    },
    explanation: 'Turns the complete six-line figure upside down.',
    implementationStatus: 'available',
    resultKind: 'single-hexagram',
  },
  {
    id: 'trigram-exchange',
    nameEnglish: 'Exchanged Trigrams',
    nameChinese: '交卦',
    aliases: ['upper-lower exchange'],
    family: 'core',
    transformationClass: 'intrinsic',
    requirement: 'hexagram-only',
    provenance: {
      tradition: 'Classical structural',
      sourceIds: structuralSourceIds,
      canonicality: 'variant',
    },
    explanation: 'Exchanges the lower and upper three-line groups.',
    implementationStatus: 'available',
    resultKind: 'single-hexagram',
  },
  {
    id: 'symmetry-family',
    nameEnglish: 'Eightfold Symmetry Family',
    aliases: ['structural orbit'],
    family: 'symmetry',
    transformationClass: 'current-formalization',
    requirement: 'hexagram-only',
    provenance: {
      tradition: 'Current formalization',
      sourceIds: ['docs:YIJING_TRANSFORMATIONS'],
      canonicality: 'current-formalization',
    },
    explanation:
      'Groups the distinct results of complement, reversal, exchange, and their explicit compositions.',
    implementationStatus: 'available',
    resultKind: 'multiple-hexagrams',
  },
  {
    id: 'king-wen-pair',
    nameEnglish: 'King Wen Pair',
    aliases: ['sequence pair'],
    family: 'textual-relation',
    transformationClass: 'textual-relation',
    requirement: 'hexagram-only',
    provenance: {
      tradition: 'Textual relation',
      sourceIds: ['current:canonical-hexagram-registry'],
      canonicality: 'widely-attested',
    },
    explanation: 'Pairs consecutive figures as 1–2, 3–4, through 63–64.',
    implementationStatus: 'available',
    resultKind: 'textual-relation',
  },
  {
    id: 'king-wen-previous',
    nameEnglish: 'Previous King Wen Hexagram',
    aliases: ['previous sequence neighbor'],
    family: 'textual-relation',
    transformationClass: 'textual-relation',
    requirement: 'hexagram-only',
    provenance: {
      tradition: 'Textual relation',
      sourceIds: ['current:canonical-hexagram-registry'],
      canonicality: 'widely-attested',
    },
    explanation: 'The immediately preceding figure without sequence wraparound.',
    implementationStatus: 'available',
    resultKind: 'textual-relation',
  },
  {
    id: 'king-wen-next',
    nameEnglish: 'Next King Wen Hexagram',
    aliases: ['next sequence neighbor'],
    family: 'textual-relation',
    transformationClass: 'textual-relation',
    requirement: 'hexagram-only',
    provenance: {
      tradition: 'Textual relation',
      sourceIds: ['current:canonical-hexagram-registry'],
      canonicality: 'widely-attested',
    },
    explanation: 'The immediately following figure without sequence wraparound.',
    implementationStatus: 'available',
    resultKind: 'textual-relation',
  },
  {
    id: 'zagua-contrast',
    nameEnglish: 'Zagua Contrast',
    nameChinese: '雜卦',
    aliases: ['miscellaneous hexagrams contrast'],
    family: 'textual-relation',
    transformationClass: 'textual-relation',
    requirement: 'source-table',
    provenance: {
      tradition: 'Textual relation',
      sourceIds: [],
      canonicality: 'source-required',
    },
    explanation: 'Requires a reviewed source table preserving the received textual contrasts.',
    implementationStatus: 'source-needed',
    resultKind: 'textual-relation',
  },
  {
    id: 'lower-four-line-interior',
    nameEnglish: 'Lower Four-Line Interior',
    aliases: [],
    family: 'interior',
    transformationClass: 'current-formalization',
    requirement: 'hexagram-only',
    provenance: {
      tradition: 'Current formalization',
      sourceIds: ['docs:YIJING_TRANSFORMATIONS'],
      canonicality: 'current-formalization',
    },
    explanation: 'Projects lines 1–4 into overlapping lower and upper trigrams.',
    implementationStatus: 'available',
    resultKind: 'single-hexagram',
  },
  {
    id: 'upper-four-line-interior',
    nameEnglish: 'Upper Four-Line Interior',
    aliases: [],
    family: 'interior',
    transformationClass: 'current-formalization',
    requirement: 'hexagram-only',
    provenance: {
      tradition: 'Current formalization',
      sourceIds: ['docs:YIJING_TRANSFORMATIONS'],
      canonicality: 'current-formalization',
    },
    explanation: 'Projects lines 3–6 into overlapping lower and upper trigrams.',
    implementationStatus: 'available',
    resultKind: 'single-hexagram',
  },
  {
    id: 'lower-five-line-interior',
    nameEnglish: 'Lower Five-Line Interior',
    aliases: [],
    family: 'interior',
    transformationClass: 'current-formalization',
    requirement: 'hexagram-only',
    provenance: {
      tradition: 'Current formalization',
      sourceIds: ['docs:YIJING_TRANSFORMATIONS'],
      canonicality: 'current-formalization',
    },
    explanation: 'Projects the lower five source lines into a six-line figure.',
    implementationStatus: 'available',
    resultKind: 'single-hexagram',
  },
  {
    id: 'upper-five-line-interior',
    nameEnglish: 'Upper Five-Line Interior',
    aliases: [],
    family: 'interior',
    transformationClass: 'current-formalization',
    requirement: 'hexagram-only',
    provenance: {
      tradition: 'Current formalization',
      sourceIds: ['docs:YIJING_TRANSFORMATIONS'],
      canonicality: 'current-formalization',
    },
    explanation: 'Projects the upper five source lines into a six-line figure.',
    implementationStatus: 'available',
    resultKind: 'single-hexagram',
  },
  {
    id: 'deep-nuclear',
    nameEnglish: 'Deep Nuclear Core',
    aliases: ['iterated mutual'],
    family: 'interior',
    transformationClass: 'current-formalization',
    requirement: 'hexagram-only',
    provenance: {
      tradition: 'Current formalization',
      sourceIds: ['docs:YIJING_TRANSFORMATIONS'],
      canonicality: 'current-formalization',
    },
    explanation: 'Iterates the traditional nuclear operation until a line signature repeats.',
    implementationStatus: 'available',
    resultKind: 'multiple-hexagrams',
  },
  {
    id: 'transformation-paths',
    nameEnglish: 'Transformation Paths',
    aliases: ['minimal line-change orders'],
    family: 'current-computational',
    transformationClass: 'current-formalization',
    requirement: 'selected-destination',
    provenance: {
      tradition: 'Current formalization',
      sourceIds: ['docs:YIJING_TRANSFORMATIONS'],
      canonicality: 'current-formalization',
    },
    explanation: 'Enumerates minimal orders for changing exactly the differing lines.',
    implementationStatus: 'available',
    resultKind: 'multiple-hexagrams',
  },
  {
    id: 'structure-anatomy',
    nameEnglish: 'Structural Anatomy',
    aliases: ['line positions'],
    family: 'structure',
    transformationClass: 'intrinsic',
    requirement: 'hexagram-only',
    provenance: {
      tradition: 'Classical structural',
      sourceIds: ['docs:YIJING_TRANSFORMATIONS'],
      canonicality: 'widely-attested',
    },
    explanation: 'Describes position, centrality, correspondence, and Three Powers grouping.',
    implementationStatus: 'available',
    resultKind: 'analysis',
  },
] as const satisfies readonly TransformationDefinition[]

const definitionsById = new Map<string, TransformationDefinition>(
  TRANSFORMATION_DEFINITIONS.map((definition) => [definition.id, definition]),
)

export const getTransformationDefinition = (id: string): TransformationDefinition => {
  const definition = definitionsById.get(id)
  if (!definition) {
    throw new Error(`Unknown transformation definition: ${id}`)
  }
  return definition
}
